describe('VP_About and VP_Orberg', function () {
  function boot() {
    var env = load('all', { search: '?mock=1&debug=1' });
    var W = env.window;
    var D = W.VP_Dom;
    env.app = D.el('div', { id: 'app', className: 'vp-app' });
    env.main = D.el('main', { id: 'vp-main' });
    env.app.appendChild(env.main);
    env.document.body.appendChild(env.app);
    W.VP_MockEngine.options.latencyMs = 1;
    W.VP_App.boot({ root: env.main, status: D.el('div') });
    env.clock.tick(500);
    env.sent = [];
    var call = W.VP_Bridge.call;
    W.VP_Bridge.call = function (cmd, params) {
      env.sent.push({ cmd: cmd, params: params });
      return call(cmd, params);
    };
    env.cmds = function (name) { return env.sent.filter(function (s) { return s.cmd === name; }); };
    env.q = function (sel) { return env.document.querySelector(sel); };
    env.qa = function (sel) { return env.document.querySelectorAll(sel); };
    return env;
  }

  it('About: tabs by keyboard, version from engine.hello, the lexicon notices rendered verbatim, software and font entries, OFL.txt over XHR, links through shell.openExternal', function () {
    var env = boot();
    var W = env.window;
    W.VP_About.open();
    eq(env.q('.vp-dialog-title').textContent, 'About vetus poeta');
    eq(W.VP_About.tab(), 'about');
    ok(env.q('.vp-about-mark .vp-lockup'), 'SVG lockup');
    eq(env.q('.vp-about-mark .vp-lockup').getAttribute('aria-label'), 'vetus poeta');
    ok(env.q('#vp-about-body').textContent.indexOf('Version 0.0.0-mock') >= 0);
    env.key(env.q('#vp-about-tab-about'), 'ArrowRight');
    eq(W.VP_About.tab(), 'data');
    eq(env.document.activeElement, env.q('#vp-about-tab-data'));
    var notices = env.qa('.vp-about-notice');
    eq(notices.length, 2);
    var hello = W.VP_Store.get('engine').hello;
    eq(notices[0].textContent, hello.lexicons[0].notice, 'verbatim');
    eq(notices[1].textContent, hello.lexicons[1].notice);
    ok(notices[0].textContent.indexOf('DCC') > 0 && notices[0].textContent.indexOf('Whitaker') > 0);
    ok(env.qa('.vp-about-lex h4')[0].textContent.indexOf('Latin dictionary') === 0);
    W.VP_About.setTab('software');
    var names = env.qa('.vp-about-name').map(function (n) { return n.textContent; });
    deepEq(names.slice(0, 4), ['llama.cpp', 'miniz', 'nlohmann/json', 'doctest']);
    ok(env.q('#vp-about-body').textContent.indexOf('Apache-2.0') > 0);
    ok(env.q('#vp-about-body').textContent.indexOf('WebView2') > 0);
    env.qa('.vp-about-entry')[0].querySelector('[data-about-url]').click();
    env.clock.tick(50);
    eq(env.cmds('shell.openExternal')[0].params.url, 'https://github.com/ggml-org/llama.cpp');
    W.VP_About.setTab('fonts');
    eq(env.q('.vp-about-name').textContent, 'Gentium Plus');
    ok(env.q('.vp-about-licence').textContent.indexOf('OFL') > 0 || env.q('.vp-about-licence').textContent.indexOf('Open Font License') > 0);
    var show = env.q('[data-about-file]');
    show.click();
    env.clock.tick(50);
    eq(show.getAttribute('aria-expanded'), 'true');
    eq(show.textContent, 'Hide licence text');
    var pre = env.q('.vp-about-licfile .vp-about-notice');
    ok(!pre.hidden);
    ok(pre.textContent.indexOf('SIL OPEN FONT LICENSE') >= 0, 'fonts/OFL.txt loaded: ' + pre.textContent.slice(0, 60));
    deepEq(W.VP_I18n.missing(), []);
    W.VP_About.close();
    eq(W.VP_Dialog.count(), 0);
    eq(env.errors().length, 0);
  });

  it('Orbergise: three panes, options kept in settings and sent with orbergise.start, changed words underlined, meaning chip from cue.get, "was -> now" in the Word tab', function () {
    var env = boot();
    var W = env.window;
    var O = W.VP_Orberg;
    deepEq(O.meaningChip({ percent: 100, missing: [] }), { kind: 'ok', percent: 100, missing: [] });
    eq(O.meaningChip({ percent: 75, missing: ['habitō'] }).kind, 'check');
    eq(O.meaningChip({ percent: 40 }).kind, 'fix');
    eq(O.meaningChip(null).kind, 'none');
    env.q('#vp-start-orberg').checked = true;
    env.fire(env.q('#vp-start-orberg'), 'change');
    env.q('[data-start-action="sample"]').click();
    env.clock.tick(300);
    eq(W.VP_Workspace.mode(), 'orberg');
    ok(O.isMounted());
    eq(env.qa('.vp-orb-body .vp-pane').length, 3, 'three stacked panes');
    eq(env.q('#vp-orb-src-title').textContent, 'Latin file');
    ok(env.q('.vp-orb-orig').textContent.indexOf('not loaded') >= 0);
    ok(env.q('#vp-orb-version').textContent.indexOf('Not rewritten yet') >= 0);
    eq(env.q('[data-orb-tier="2"]').getAttribute('aria-pressed'), 'true');
    env.q('[data-orb-tier="1"]').click();
    env.clock.tick(50);
    eq(W.VP_Store.get('settings').orberg.tier, 1);
    env.q('#vp-orb-simplify').click();
    env.clock.tick(50);
    eq(W.VP_Store.get('settings').orberg.simplify, false);
    env.q('#vp-orb-simplify').click();
    env.clock.tick(50);
    env.q('#vp-orb-run').click();
    env.clock.tick(3000);
    var start = env.cmds('orbergise.start');
    eq(start.length, 1);
    deepEq(start[0].params, { tier: 1, keepNames: true, simplify: true });
    eq(env.cmds('translate.start').length, 0);
    W.VP_Toast.clearAll();
    W.VP_CueList.select(1);
    env.clock.tick(100);
    eq(W.VP_Store.getCue(1).target, 'Nauta in īnsulā vīvit.');
    var changed = env.qa('#vp-orb-version .vp-word-changed');
    eq(changed.length, 1);
    eq(changed[0].textContent, 'vīvit');
    eq(changed[0].getAttribute('title'), 'Was habitat, now vīvit');
    ok(env.q('#vp-orb-version .vp-tier'), 'tier badge next to the changed word');
    eq(env.q('.vp-orb-chip').textContent, 'Meaning kept: 67%');
    ok(env.q('.vp-orb-chip').classList.contains('vp-chip-check'));
    ok(env.q('.vp-orb-missinglist').textContent.indexOf('habitō') > 0, 'missing lemma listed');
    changed[0].click();
    env.clock.tick(100);
    eq(W.VP_Workspace.tab(), 'word');
    var insp = env.q('#vp-panel-body').textContent;
    ok(insp.indexOf('Changed by Orbergise') >= 0, insp.slice(0, 200));
    ok(insp.indexOf('habitat') >= 0 && insp.indexOf('vīvit') >= 0, 'was -> now');
    ok(insp.indexOf('simpler word with the same meaning') > 0, 'reason');
    W.VP_CueList.select(0);
    env.clock.tick(100);
    eq(env.q('.vp-orb-chip').textContent, 'Meaning kept: 100%');
    eq(env.qa('#vp-orb-version .vp-word-changed').length, 1, 'videt -> spectat');
    ok(O.startEdit());
    eq(env.document.activeElement, env.q('#vp-orb-editor'));
    env.q('#vp-orb-editor').value = 'Puella rosam amat.';
    O.acceptEdit();
    env.clock.tick(100);
    eq(W.VP_Store.getCue(0).target, 'Puella rosam amat.');
    eq(W.VP_Store.getCue(0).state, 'edited');
    env.q('[data-orb-action="choose"]').click();
    env.clock.tick(3000);
    eq(env.cmds('dialog.openFile')[0].params.kind, 'original');
    start = env.cmds('orbergise.start');
    eq(start.length, 2);
    eq(start[1].params.originalPath, 'C:\\Users\\Teacher\\Videos\\lesson-3.en.srt');
    W.VP_Toast.clearAll();
    W.VP_CueList.select(2);
    env.clock.tick(100);
    eq(env.q('.vp-orb-orig').textContent, 'The farmer carries water.', 'original-language line from cue.get');
    eq(env.q('[data-orb-action="choose"]').hidden, true);
    deepEq(W.VP_I18n.missing(), []);
    env.q('#vp-tab-translate').click();
    eq(O.isMounted(), false, 'leaving the mode destroys the panes');
    W.VP_Workspace.close();
    env.clock.tick(300);
    deepEq(W.VP_Debug.failures(), []);
    eq(env.errors().length, 0);
  });
});
