describe('VP_Workspace', function () {
  // Boots the whole app with the mock engine, as index.html does.
  function boot(before) {
    var env = load('all', { search: '?mock=1&debug=1' });
    var W = env.window;
    var D = W.VP_Dom;
    env.app = D.el('div', { id: 'app', className: 'vp-app' });
    env.main = D.el('main', { id: 'vp-main' });
    env.status = D.el('div', { id: 'vp-status' });
    env.app.appendChild(env.main);
    env.app.appendChild(env.status);
    env.document.body.appendChild(env.app);
    W.VP_MockEngine.options.latencyMs = 1;
    if (before) { before(env); }
    W.VP_App.boot({ root: env.main, status: env.status });
    env.clock.tick(500);
    env.sent = [];
    var call = W.VP_Bridge.call;
    W.VP_Bridge.call = function (cmd, params) {
      env.sent.push({ cmd: cmd, params: params });
      return call(cmd, params);
    };
    env.cmds = function (name) { return env.sent.filter(function (s) { return s.cmd === name; }); };
    env.q = function (sel) { return env.document.querySelector(sel); };
    env.press = function (key, mods, target) {
      env.key(target || env.document.activeElement || env.document.body, key, mods);
      env.clock.tick(60);
    };
    return env;
  }
  function openSample(env) {
    env.window.VP_Start.openSample();
    env.clock.tick(300);
    eq(env.window.VP_Router.current(), 'workspace');
  }
  function translateAll(env) {
    env.q('#vp-translate').click();
    env.clock.tick(3000);
  }

  it('opening the sample routes to the workspace; the wordmark closes it and routes back with every count at its baseline', function () {
    var env = boot();
    var W = env.window;
    eq(W.VP_Router.current(), 'start');
    var base = W.VP_Router.counts();
    var nodes = W.VP_Debug.stats().domNodes;
    openSample(env);
    ok(env.app.classList.contains('vp-app-ws'), 'app frame in workspace mode');
    eq(env.q('.vp-ws-name').textContent, 'sample.en.srt');
    eq(env.q('.vp-ws-pair').textContent, 'English → Latin');
    eq(env.q('#vp-tab-translate').getAttribute('aria-selected'), 'true');
    eq(W.VP_Store.cueCount(), 12);
    eq(W.VP_CueList.selected(), 0);
    eq(env.q('#vp-translate').textContent, 'Translate 12 cues');
    eq(env.q('.vp-ws-autosave').getAttribute('aria-live'), 'polite');
    eq(env.q('.vp-ws-autosave').textContent, 'Not saved yet');
    ok(env.q('.vp-ws-counts').textContent.indexOf('0 / 12 translated') === 0, env.q('.vp-ws-counts').textContent);
    ok(env.q('.vp-ws-engines').textContent.indexOf('Rules on') === 0);
    ok(env.q('.vp-ws-status .vp-net-offline'), 'offline indicator');
    ok(W.VP_Debug.stats().domNodes <= 800);
    env.q('.vp-ws-home').click();
    env.clock.tick(300);
    eq(W.VP_Router.current(), 'start');
    eq(W.VP_Store.get('project'), null);
    eq(W.VP_Store.cueCount(), 0);
    eq(W.VP_History.size(), 0);
    ok(!env.app.classList.contains('vp-app-ws'));
    deepEq(W.VP_Router.counts(), base);
    eq(W.VP_Debug.stats().domNodes, nodes);
    deepEq(W.VP_Debug.failures(), []);
    for (var i = 0; i < 10; i++) {
      openSample(env);
      W.VP_Workspace.close();
      env.clock.tick(300);
    }
    deepEq(W.VP_Router.counts(), base, 'ten open/close cycles leak nothing');
    deepEq(W.VP_Debug.failures(), []);
    deepEq(W.VP_I18n.missing(), []);
    eq(env.errors().length, 0);
  });

  it('Translate: progress with cues/s, ETA and Cancel; when done, the first cue to review is selected under "Needs review (n)"', function () {
    var env = boot(function (e) {
      e.window.VP_MockEngine.options.cuesPerSecond = 20;
      e.window.VP_MockEngine.options.batch = 4;
    });
    var W = env.window;
    openSample(env);
    env.q('#vp-translate').click();
    env.clock.tick(260);
    ok(!env.q('.vp-job-run').hidden, 'progress shown');
    ok(env.q('.vp-job-idle').hidden);
    var text = env.q('.vp-job-text').textContent;
    ok(/^4 of 12 cues · [\d.]+ cues\/s · about \d+ seconds? left$/.test(text), text);
    eq(env.q('.vp-job-progress').getAttribute('aria-valuenow'), '33');
    ok(/width: 33%|33%/.test(env.q('.vp-job-progress .vp-progress-bar').style.width), 'bar width');
    eq(env.q('.vp-job-progress').getAttribute('role'), 'progressbar');
    eq(W.VP_Store.getCue(0).state, 'translated', 'rows fill as cues arrive');
    env.q('.vp-job-run [data-ws-action="cancel"]').click();
    env.clock.tick(300);
    eq(env.cmds('translate.cancel').length, 1);
    ok(env.q('.vp-job-run').hidden, 'idle again');
    ok(env.q('.vp-toast-text').textContent.indexOf('Translation stopped after') === 0);
    eq(env.q('#vp-translate').getAttribute('data-scope'), 'rest');
    env.q('#vp-translate').click();
    env.clock.tick(3000);
    var start = env.cmds('translate.start');
    eq(start.length, 2);
    eq(start[1].params.indices.length, 12 - 4, 'only the cues still to translate');
    var first = W.VP_CueList.firstReview();
    ok(first >= 0);
    eq(W.VP_CueList.filter(), 'review');
    eq(W.VP_CueList.selected(), first);
    var n = W.VP_CueList.counts().review;
    eq(env.q('#vp-cl-filter').value, 'review');
    var opt = env.document.querySelectorAll('#vp-cl-filter option').filter(function (o) { return o.value === 'review'; })[0];
    eq(opt.textContent, 'Needs review (' + n + ')');
    eq(env.q('#vp-translate').textContent, 'Translate all again');
    ok(env.q('.vp-ws-counts').textContent.indexOf('12 / 12 translated') === 0);
  });

  it('dispatches the PREDESIGN 4.3 shortcuts: moves, review, accept, edit, alternatives, search, view toggles, undo/redo', function () {
    var env = boot();
    var W = env.window;
    var L = W.VP_CueList;
    var Pn = W.VP_Panes;
    openSample(env);
    translateAll(env);
    L.setFilter('all');
    L.select(0);
    L.focusList();
    env.press('ArrowDown');
    eq(L.selected(), 1);
    env.press('j');
    eq(L.selected(), 2);
    env.press('k');
    env.press('ArrowUp');
    eq(L.selected(), 0);
    var reviewList = L.viewIndices().filter(function (i) { return W.VP_CueList.needsReview(W.VP_Store.getCue(i)); });
    ok(reviewList.length >= 2, 'mock gives at least two cues to review: ' + reviewList.length);
    env.press('ArrowDown', { ctrl: true });
    eq(L.selected(), reviewList[0] === 0 ? reviewList[1] : reviewList[0]);
    env.press('ArrowUp', { ctrl: true });
    L.select(reviewList[0]);
    env.press('Enter');
    deepEq(env.cmds('cue.review')[0].params, { indices: [reviewList[0]], reviewed: true });
    eq(W.VP_Store.getCue(reviewList[0]).state, 'reviewed');
    eq(W.VP_History.size(), 1);
    env.press('z', { ctrl: true });
    eq(env.cmds('history.undo').length, 1);
    eq(W.VP_Store.getCue(reviewList[0]).state, 'translated', 'undo');
    env.press('y', { ctrl: true });
    eq(W.VP_Store.getCue(reviewList[0]).state, 'reviewed', 'redo');
    env.press('Z', { ctrl: true, shift: true });
    eq(env.cmds('history.redo').length, 2, 'Ctrl+Shift+Z is redo too');
    eq(W.VP_Store.getCue(reviewList[0]).state, 'reviewed', 'nothing left to redo');
    L.select(reviewList[0]);
    W.VP_Store.putCues([(function () { var c = JSON.parse(JSON.stringify(W.VP_Store.getCue(reviewList[0]))); c.state = 'translated'; return c; }())]);
    env.press('Enter', { shift: true });
    eq(L.selected(), reviewList[1], 'Shift+Enter accepts and goes to the next cue to review');
    env.press('e');
    eq(Pn.mode(), 'edit');
    env.press('z', { ctrl: true });
    eq(env.cmds('history.undo').length, 1, 'Ctrl+Z in the editor is the textarea undo');
    env.press('Escape');
    eq(Pn.mode(), 'view');
    env.press('e');
    Pn.setEditorText('Avis cantat.');
    env.press('Enter', { ctrl: true });
    eq(Pn.mode(), 'remember');
    eq(W.VP_Store.getCue(reviewList[1]).target, 'Avis cantat.');
    env.press('Escape');
    eq(Pn.mode(), 'view', 'Esc dismisses the remember chip');
    L.select(0);
    env.clock.tick(60);
    var alt = Pn.alternatives()[0];
    env.document.body.focus();
    env.press('1', null, env.document.body);
    eq(env.cmds('cue.choose').length, 1);
    eq(W.VP_Store.getCue(0).target, alt.text);
    env.press('f', { ctrl: true });
    eq(env.document.activeElement, env.q('#vp-cl-search'));
    env.press('m', { ctrl: true });
    eq(W.VP_Store.get('settings').showMacrons, false);
    env.clock.tick(100);
    env.press('e', { ctrl: true });
    eq(W.VP_Store.get('settings').showEmoji, false);
    env.press('m', { ctrl: true });
    eq(W.VP_Store.get('settings').showMacrons, true);
    var reviews = env.cmds('cue.review').length;
    env.q('#vp-translate').focus();
    env.press('Enter');
    eq(env.cmds('cue.review').length, reviews, 'Enter on a button presses the button, it does not accept');
    deepEq(W.VP_I18n.missing(), []);
    eq(env.errors().length, 0);
  });

  it('top bar: tabs, drawer toggle (Esc closes), undo/redo buttons, save with a chosen path, autosave notice', function () {
    var env = boot();
    var W = env.window;
    openSample(env);
    env.q('#vp-tab-orberg').click();
    eq(W.VP_Workspace.mode(), 'orberg');
    ok(env.q('#vp-tab-translate-panel').hidden);
    ok(!env.q('#vp-tab-orberg-panel').hidden);
    ok(env.q('#vp-tab-orberg-panel').textContent.indexOf('coming soon') > 0);
    env.key(env.q('#vp-tab-orberg'), 'ArrowLeft');
    eq(W.VP_Workspace.mode(), 'translate');
    eq(env.document.activeElement, env.q('#vp-tab-translate'));
    var btn = env.q('.vp-ws-drawer-btn');
    btn.click();
    eq(W.VP_Workspace.drawerOpen(), true);
    eq(btn.getAttribute('aria-expanded'), 'true');
    eq(env.q('.vp-ws').getAttribute('data-drawer'), 'open');
    env.press('Escape');
    eq(W.VP_Workspace.drawerOpen(), false);
    eq(env.document.activeElement, btn);
    ok(W.VP_Workspace.panelHost(), 'panel host for the right-panel tabs');
    ok(env.q('.vp-ws-undo').disabled);
    translateAll(env);
    W.VP_CueList.select(0);
    env.press('Enter', null, env.document.body);
    ok(!env.q('.vp-ws-undo').disabled);
    ok(env.q('.vp-ws-undo').getAttribute('title').indexOf('Undo “Accept cue”') === 0);
    env.q('.vp-ws-undo').click();
    env.clock.tick(60);
    eq(W.VP_Store.getCue(0).state, 'translated');
    ok(!env.q('.vp-ws-redo').disabled);
    eq(env.q('.vp-ws-save').textContent, 'Unsaved changes (autosave on)');
    env.clock.tick(1500);
    ok(/^Autosaved \d\d:\d\d$/.test(env.q('.vp-ws-autosave').textContent), env.q('.vp-ws-autosave').textContent);
    env.press('s', { ctrl: true });
    env.clock.tick(100);
    eq(env.cmds('dialog.saveFile').length, 1);
    eq(env.cmds('project.saveAs')[0].params.path, 'C:\\Users\\Student\\Documents\\sample.en.vpoeta');
    ok(/^Saved \d\d:\d\d$/.test(env.q('.vp-ws-save').textContent), env.q('.vp-ws-save').textContent);
    eq(W.VP_Store.get('project').path, 'C:\\Users\\Student\\Documents\\sample.en.vpoeta');
    W.VP_Workspace.close();
    env.clock.tick(300);
    var rows = W.VP_Start.recentRows();
    eq(rows[0].path, 'C:\\Users\\Student\\Documents\\sample.en.vpoeta');
    eq(rows[0].cues, 12);
    eq(rows[0].translated, 12);
    ok(env.q('.vp-recent-row').textContent.indexOf('12 / 12 cues') > 0, env.q('.vp-recent-row').textContent);
  });

  it('the gear and ? buttons open dialogs; Export and Settings shortcuts open placeholders', function () {
    var env = boot();
    var W = env.window;
    openSample(env);
    env.q('[data-ws-action="settings"]').click();
    eq(W.VP_Dialog.count(), 1);
    eq(env.q('.vp-dialog-title').textContent, 'Settings');
    W.VP_Dialog.closeAll();
    env.q('[data-ws-action="help"]').click();
    eq(env.q('.vp-dialog-title').textContent, 'Keyboard shortcuts');
    W.VP_Dialog.closeAll();
    env.press('E', { ctrl: true, shift: true }, env.document.body);
    eq(env.q('.vp-dialog-title').textContent, 'Export');
    W.VP_Dialog.closeAll();
    eq(W.VP_Dialog.count(), 0);
  });
});
