// UTF-8 helpers and the normalisation contract of DESIGN.md section 4. See vp/text.h.
// Table driven: src/nfc_table.h is generated by tools/gen_nfc_table.py from Python's unicodedata, so the C++ keys
// agree with tools/build_library/vptext.py byte for byte inside the supported ranges.
#include "vp/text.h"

#include <algorithm>

#include "nfc_table.h"

namespace vp {
namespace text {

namespace {

using namespace text_tables;

constexpr char32_t kDirect = 0x2000;  // direct-index tables cover U+0000..U+1FFF

struct Tables {
  uint16_t decomp[kDirect];  // index + 1 into kDecomp, 0 = none
  uint8_t ccc[kDirect];
  uint16_t lower[kDirect];   // index + 1 into kLower, 0 = unchanged
  Tables() {
    std::fill(decomp, decomp + kDirect, uint16_t(0));
    std::fill(ccc, ccc + kDirect, uint8_t(0));
    std::fill(lower, lower + kDirect, uint16_t(0));
    for (size_t i = 0; i < sizeof(kDecomp) / sizeof(kDecomp[0]); ++i) decomp[kDecomp[i].cp] = uint16_t(i + 1);
    for (const Ccc& c : kCcc) ccc[c.cp] = c.ccc;
    for (size_t i = 0; i < sizeof(kLower) / sizeof(kLower[0]); ++i)
      if (kLower[i].cp < kDirect) lower[kLower[i].cp] = uint16_t(i + 1);
  }
};

const Tables& tables() {
  static const Tables t;
  return t;
}

template <size_t N>
bool inRanges(const Range (&r)[N], char32_t cp) {
  const Range* it = std::upper_bound(r, r + N, uint32_t(cp), [](uint32_t v, const Range& x) { return v < x.lo; });
  if (it == r) return false;
  --it;
  return cp <= it->hi;
}

inline uint8_t cccOf(const Tables& t, char32_t cp) { return cp < kDirect ? t.ccc[cp] : 0; }

bool isAlpha(char32_t cp) {
  if (cp < 0x80) return (cp >= 'a' && cp <= 'z') || (cp >= 'A' && cp <= 'Z');
  return inRanges(kAlpha, cp);
}

char32_t composePair(char32_t a, char32_t b) {
  if (a >= kDirect || b < 0x300 || b > 0x36F) return 0;
  const uint32_t key = (uint32_t(a) << 16) | uint32_t(b);
  const size_t n = sizeof(kPairs) / sizeof(kPairs[0]);
  const Pair* it = std::lower_bound(kPairs, kPairs + n, key, [](const Pair& p, uint32_t k) { return p.key < k; });
  if (it != kPairs + n && it->key == key) return it->composite;
  return 0;
}

void decodeAll(std::string_view s, std::u32string& out) {
  out.clear();
  size_t i = 0;
  while (i < s.size()) out.push_back(decodeUtf8(s, i));
}

void encodeAll(const std::u32string& in, std::string& out) {
  out.clear();
  for (char32_t c : in) appendUtf8(out, c);
}

// Full canonical decomposition + canonical ordering (NFD) of `in` into `out`.
void nfdBuf(const std::u32string& in, std::u32string& out) {
  const Tables& t = tables();
  out.clear();
  for (char32_t c : in) {
    if (c < kDirect && t.decomp[c]) {
      const Decomp& d = kDecomp[t.decomp[c] - 1];
      for (uint8_t k = 0; k < d.len; ++k) out.push_back(d.d[k]);
    } else {
      out.push_back(c);
    }
  }
  // Canonical ordering: stable insertion sort of each run of non-starters by combining class.
  for (size_t i = 1; i < out.size(); ++i) {
    const uint8_t ci = cccOf(t, out[i]);
    if (ci == 0) continue;
    size_t j = i;
    while (j > 0) {
      const uint8_t cp = cccOf(t, out[j - 1]);
      if (cp == 0 || cp <= ci) break;
      std::swap(out[j - 1], out[j]);
      --j;
    }
  }
}

// Canonical composition of an NFD buffer, in place (the UAX #15 algorithm).
void composeInPlace(std::u32string& buf) {
  if (buf.empty()) return;
  const Tables& t = tables();
  size_t starterPos = 0;
  char32_t starter = buf[0];
  int lastClass = cccOf(t, starter);
  if (lastClass != 0) lastClass = 256;  // a leading non-starter can never be composed with
  size_t w = 1;
  for (size_t r = 1; r < buf.size(); ++r) {
    const char32_t ch = buf[r];
    const int chClass = cccOf(t, ch);
    if (lastClass != 256 && (lastClass < chClass || lastClass == 0)) {
      const char32_t comp = composePair(starter, ch);
      if (comp) {
        buf[starterPos] = comp;
        starter = comp;
        continue;
      }
    }
    if (chClass == 0) {
      starterPos = w;
      starter = ch;
    }
    lastClass = chClass;
    buf[w++] = ch;
  }
  buf.resize(w);
}

bool sigmaIgnorable(char32_t c) { return inRanges(kSigmaIgnorable, c); }
bool sigmaCased(char32_t c) { return inRanges(kSigmaCased, c); }

// Python str.lower: full mappings + Final_Sigma for U+03A3.
void lowerBuf(const std::u32string& in, std::u32string& out) {
  const Tables& t = tables();
  out.clear();
  const size_t n = in.size();
  for (size_t i = 0; i < n; ++i) {
    const char32_t c = in[i];
    if (c < 0x80) {
      out.push_back((c >= 'A' && c <= 'Z') ? c + 32 : c);
      continue;
    }
    if (c == 0x3A3) {
      size_t j = i;
      while (j > 0 && sigmaIgnorable(in[j - 1])) --j;
      bool fin = j > 0 && sigmaCased(in[j - 1]);
      if (fin) {
        size_t k = i + 1;
        while (k < n && sigmaIgnorable(in[k])) ++k;
        fin = k == n || !sigmaCased(in[k]);
      }
      out.push_back(fin ? 0x3C2 : 0x3C3);
      continue;
    }
    const Lower* m = nullptr;
    if (c < kDirect) {
      if (t.lower[c]) m = &kLower[t.lower[c] - 1];
    } else {
      const size_t nl = sizeof(kLower) / sizeof(kLower[0]);
      const Lower* it = std::lower_bound(kLower, kLower + nl, uint32_t(c), [](const Lower& x, uint32_t v) { return x.cp < v; });
      if (it != kLower + nl && it->cp == c) m = it;
    }
    if (m) {
      for (uint8_t k = 0; k < m->len; ++k) out.push_back(m->to[k]);
    } else {
      out.push_back(c);
    }
  }
}

// Per-thread scratch so that the caller-provided-output overloads do not allocate after warm-up.
struct Scratch {
  std::u32string a, b;
};
Scratch& scratch() {
  thread_local Scratch s;
  return s;
}

enum : unsigned {
  kStripLength = 1u,      // U+0304 U+0306
  kStripGreek = 2u,       // greek_bare marks
  kStripAllMarks = 4u,    // every U+0300-036F
};

bool stripped(char32_t c, unsigned mask) {
  if (c < 0x300 || c > 0x36F) return false;
  if ((mask & kStripAllMarks) != 0) return true;
  if ((mask & kStripLength) != 0 && (c == 0x304 || c == 0x306)) return true;
  if ((mask & kStripGreek) != 0) {
    switch (c) {
      case 0x300: case 0x301: case 0x302: case 0x308: case 0x313: case 0x314: case 0x342: case 0x343: case 0x344:
      case 0x345:
        return true;
      default:
        return false;
    }
  }
  return false;
}

enum class Post { None, Latin, Quotes };

// The shared key pipeline: [nfc] -> [lower] -> [sigma fold] -> [NFD, strip, NFC] -> post-processing.
void pipeline(std::string_view s, bool doLower, bool sigmaFold, unsigned strip, Post post, std::string& out) {
  Scratch& sc = scratch();
  std::u32string& a = sc.a;
  std::u32string& b = sc.b;
  decodeAll(s, a);
  nfdBuf(a, b);
  composeInPlace(b);  // b = nfc(s)
  if (doLower) {
    lowerBuf(b, a);
    a.swap(b);
  }
  if (sigmaFold)
    for (char32_t& c : b)
      if (c == 0x3C2) c = 0x3C3;
  if (strip) {
    nfdBuf(b, a);
    size_t w = 0;
    for (size_t r = 0; r < a.size(); ++r)
      if (!stripped(a[r], strip)) a[w++] = a[r];
    a.resize(w);
    composeInPlace(a);
    a.swap(b);
  }
  out.clear();
  for (char32_t c : b) {
    switch (post) {
      case Post::Latin:
        if (c == 'j') c = 'i';
        else if (c == 'v') c = 'u';
        if (c == 0xE6) { out += "ae"; continue; }
        if (c == 0x153) { out += "oe"; continue; }
        if (c == '-' || c == ' ' || isAlpha(c)) appendUtf8(out, c);
        continue;
      case Post::Quotes:
        if (c == 0x2018 || c == 0x2019 || c == 0x201A || c == 0x201B) c = '\'';
        else if (c == 0x201C || c == 0x201D || c == 0x201E || c == 0x201F) c = '"';
        break;
      case Post::None:
        break;
    }
    appendUtf8(out, c);
  }
}

bool allAscii(std::string_view s) {
  for (char c : s)
    if (static_cast<unsigned char>(c) >= 0x80) return false;
  return true;
}

}  // namespace

// ---- UTF-8 --------------------------------------------------------------------------------------------------------
char32_t decodeUtf8(std::string_view s, size_t& i) {
  const size_t n = s.size();
  const unsigned char c0 = static_cast<unsigned char>(s[i]);
  if (c0 < 0x80) {
    ++i;
    return c0;
  }
  int len;
  char32_t cp;
  char32_t min;
  if (c0 >= 0xC2 && c0 <= 0xDF) { len = 2; cp = c0 & 0x1F; min = 0x80; }
  else if (c0 >= 0xE0 && c0 <= 0xEF) { len = 3; cp = c0 & 0x0F; min = 0x800; }
  else if (c0 >= 0xF0 && c0 <= 0xF4) { len = 4; cp = c0 & 0x07; min = 0x10000; }
  else { ++i; return kReplacement; }
  if (i + static_cast<size_t>(len) > n) { ++i; return kReplacement; }
  for (int k = 1; k < len; ++k) {
    const unsigned char ck = static_cast<unsigned char>(s[i + static_cast<size_t>(k)]);
    if ((ck & 0xC0) != 0x80) { ++i; return kReplacement; }
    cp = (cp << 6) | (ck & 0x3F);
  }
  if (cp < min || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) { ++i; return kReplacement; }
  i += static_cast<size_t>(len);
  return cp;
}

void appendUtf8(std::string& out, char32_t cp) {
  if (cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) cp = kReplacement;
  if (cp < 0x80) {
    out.push_back(static_cast<char>(cp));
  } else if (cp < 0x800) {
    out.push_back(static_cast<char>(0xC0 | (cp >> 6)));
    out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
  } else if (cp < 0x10000) {
    out.push_back(static_cast<char>(0xE0 | (cp >> 12)));
    out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
  } else {
    out.push_back(static_cast<char>(0xF0 | (cp >> 18)));
    out.push_back(static_cast<char>(0x80 | ((cp >> 12) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
  }
}

bool isValidUtf8(std::string_view s) {
  size_t i = 0;
  while (i < s.size()) {
    const size_t before = i;
    const char32_t c = decodeUtf8(s, i);
    if (c == kReplacement && !(i - before == 3 && s.substr(before, 3) == "\xEF\xBF\xBD")) return false;
  }
  return true;
}

std::u32string toUtf32(std::string_view s) {
  std::u32string out;
  decodeAll(s, out);
  return out;
}

std::string toUtf8(std::u32string_view s) {
  std::string out;
  out.reserve(s.size());
  for (char32_t c : s) appendUtf8(out, c);
  return out;
}

// ---- normalisation ------------------------------------------------------------------------------------------------
void nfc(std::string_view s, std::string& out) {
  if (allAscii(s)) { out.assign(s.data(), s.size()); return; }
  Scratch& sc = scratch();
  decodeAll(s, sc.a);
  nfdBuf(sc.a, sc.b);
  composeInPlace(sc.b);
  encodeAll(sc.b, out);
}

void nfd(std::string_view s, std::string& out) {
  if (allAscii(s)) { out.assign(s.data(), s.size()); return; }
  Scratch& sc = scratch();
  decodeAll(s, sc.a);
  nfdBuf(sc.a, sc.b);
  encodeAll(sc.b, out);
}

void lower(std::string_view s, std::string& out) {
  if (allAscii(s)) {
    out.assign(s.data(), s.size());
    for (char& c : out)
      if (c >= 'A' && c <= 'Z') c = static_cast<char>(c + 32);
    return;
  }
  Scratch& sc = scratch();
  decodeAll(s, sc.a);
  lowerBuf(sc.a, sc.b);
  encodeAll(sc.b, out);
}

void latin_key(std::string_view s, std::string& out) {
  if (allAscii(s)) {
    out.clear();
    for (char ch : s) {
      char c = (ch >= 'A' && ch <= 'Z') ? static_cast<char>(ch + 32) : ch;
      if (c == 'j') c = 'i';
      else if (c == 'v') c = 'u';
      if ((c >= 'a' && c <= 'z') || c == '-' || c == ' ') out.push_back(c);
    }
    return;
  }
  pipeline(s, true, false, kStripLength, Post::Latin, out);
}

void greek_key(std::string_view s, std::string& out) { pipeline(s, true, true, kStripLength, Post::None, out); }
void greek_bare(std::string_view s, std::string& out) {
  pipeline(s, true, true, kStripLength | kStripGreek, Post::None, out);
}
void en_key(std::string_view s, std::string& out) {
  if (allAscii(s)) { lower(s, out); return; }
  pipeline(s, true, false, 0, Post::Quotes, out);
}
void es_key(std::string_view s, std::string& out) { en_key(s, out); }
void es_bare(std::string_view s, std::string& out) {
  if (allAscii(s)) { lower(s, out); return; }
  pipeline(s, true, false, kStripAllMarks, Post::Quotes, out);
}
void display_latin(std::string_view form, bool macrons, std::string& out) {
  if (macrons) { nfc(form, out); return; }
  if (allAscii(form)) { out.assign(form.data(), form.size()); return; }
  pipeline(form, false, false, kStripLength, Post::None, out);
}

#define VP_TEXT_VALUE_OVERLOAD(name)          \
  std::string name(std::string_view s) {      \
    std::string out;                          \
    name(s, out);                             \
    return out;                               \
  }
VP_TEXT_VALUE_OVERLOAD(nfc)
VP_TEXT_VALUE_OVERLOAD(nfd)
VP_TEXT_VALUE_OVERLOAD(lower)
VP_TEXT_VALUE_OVERLOAD(latin_key)
VP_TEXT_VALUE_OVERLOAD(greek_key)
VP_TEXT_VALUE_OVERLOAD(greek_bare)
VP_TEXT_VALUE_OVERLOAD(en_key)
VP_TEXT_VALUE_OVERLOAD(es_key)
VP_TEXT_VALUE_OVERLOAD(es_bare)
#undef VP_TEXT_VALUE_OVERLOAD

std::string display_latin(std::string_view form, bool macrons) {
  std::string out;
  display_latin(form, macrons, out);
  return out;
}

const char* unicodeVersion() { return kUnicodeVersion; }

}  // namespace text
}  // namespace vp
