#!/usr/bin/env python3
"""Generates engine/core/src/nfc_table.h from Python's unicodedata (DESIGN.md section 4).

The C++ normaliser (engine/core/src/text.cpp) is table driven. This script emits, for the supported
NFC ranges (Latin-1 Supplement, Latin Extended-A/B, combining marks U+0300-036F, Greek and Coptic,
Latin Extended Additional, Greek Extended):
  * full canonical decompositions,
  * canonical combining classes,
  * primary composition pairs (composition exclusions and singletons are left out),
and, for all of Unicode (so keys agree with Python's str.lower / str.isalpha byte for byte):
  * full lower-case mappings (str.lower, one to three code points),
  * the two code-point classes Python's Final_Sigma rule looks at (cased, case-ignorable),
  * letter ranges (str.isalpha).

Usage: python3 engine/core/tools/gen_nfc_table.py [output]   (default: engine/core/src/nfc_table.h)
Python 3.11 stdlib only. The output is committed; rerun it only when the Python Unicode version changes.
"""
import os
import sys
import unicodedata

RANGES = [(0x0000, 0x024F), (0x0300, 0x036F), (0x0370, 0x03FF), (0x1E00, 0x1EFF), (0x1F00, 0x1FFF)]
MAX_CP = 0x10FFFF


def in_ranges(cp):
    return any(lo <= cp <= hi for lo, hi in RANGES)


def supported():
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            yield cp


def all_cps():
    for cp in range(MAX_CP + 1):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        yield cp


def full_decomp(cp):
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith('<'):
        return [cp]
    out = []
    for part in d.split():
        out.extend(full_decomp(int(part, 16)))
    return out


def ranges_of(pred):
    out = []
    start = None
    prev = None
    for cp in all_cps():
        if pred(cp):
            if start is None:
                start = cp
            elif prev != cp - 1:
                out.append((start, prev))
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out



def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'nfc_table.h')

    decomps = []
    maxlen = 0
    for cp in supported():
        d = full_decomp(cp)
        if d != [cp]:
            for x in d:
                if not in_ranges(x) and (x > 0xFFFF or unicodedata.combining(chr(x)) or full_decomp(x) != [x]):
                    raise SystemExit('decomposition of U+%04X leaves the supported ranges' % cp)
            decomps.append((cp, d))
            maxlen = max(maxlen, len(d))
    if maxlen > 4:
        raise SystemExit('decomposition longer than 4: update text.cpp')

    cccs = [(cp, unicodedata.combining(chr(cp))) for cp in supported() if unicodedata.combining(chr(cp))]

    pairs = []
    for cp in supported():
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith('<'):
            continue
        parts = [int(p, 16) for p in d.split()]
        if len(parts) != 2:
            continue
        if unicodedata.normalize('NFC', chr(cp)) != chr(cp):
            continue  # composition exclusion
        if unicodedata.combining(chr(parts[0])) != 0:
            continue  # non-starter decompositions never recompose
        if unicodedata.combining(chr(parts[1])) == 0:
            raise SystemExit('starter-starter composition U+%04X: update text.cpp' % cp)
        pairs.append(((parts[0] << 16) | parts[1], cp))
    pairs.sort()

    lowers = []
    for cp in all_cps():
        c = chr(cp)
        lo = c.lower()
        if lo != c:
            if len(lo) > 3:
                raise SystemExit('lower mapping longer than 3')
            lowers.append((cp, [ord(x) for x in lo]))

    sigma = '\u03a3'
    # Python's Final_Sigma: \p{cased}\p{case-ignorable}* SIGMA !(\p{case-ignorable}* \p{cased}).
    # A code point that is case-ignorable is skipped by both scans whether or not it is also cased, so two classes
    # suffice: "ignorable" (skipped) and "cased" (cased and not ignorable). Both are measured on str.lower itself.
    def cased(cp):
        return (chr(cp) + sigma).lower()[-1] == '\u03c2'

    def ignorable(cp):
        return not cased(cp) and ('A' + chr(cp) + sigma).lower()[-1] == '\u03c2'

    cased_r = ranges_of(cased)
    ign_r = ranges_of(ignorable)
    alpha_r = ranges_of(lambda cp: chr(cp).isalpha())

    w = []
    w.append('// Generated by engine/core/tools/gen_nfc_table.py from Python unicodedata %s. Do not edit.'
             % unicodedata.unidata_version)
    w.append('// Tables for engine/core/src/text.cpp (DESIGN.md section 4). Included by text.cpp only.')
    w.append('#pragma once')
    w.append('#include <cstdint>')
    w.append('')
    w.append('namespace vp {')
    w.append('namespace text_tables {')
    w.append('')
    w.append('constexpr const char* kUnicodeVersion = "%s";' % unicodedata.unidata_version)
    w.append('')
    w.append('struct Decomp { uint16_t cp; uint8_t len; uint16_t d[4]; };')
    w.append('struct Ccc { uint16_t cp; uint8_t ccc; };')
    w.append('struct Pair { uint32_t key; uint16_t composite; };  // key = first << 16 | second')
    w.append('struct Lower { uint32_t cp; uint32_t to[3]; uint8_t len; };')
    w.append('struct Range { uint32_t lo, hi; };')
    w.append('')
    w.append('constexpr Decomp kDecomp[] = {')
    for cp, d in decomps:
        dd = d + [0] * (4 - len(d))
        w.append('  {0x%04X, %d, {%s}},' % (cp, len(d), ', '.join('0x%04X' % x for x in dd)))
    w.append('};')
    w.append('')
    w.append('constexpr Ccc kCcc[] = {')
    for i in range(0, len(cccs), 6):
        w.append('  ' + ' '.join('{0x%04X, %d},' % x for x in cccs[i:i + 6]))
    w.append('};')
    w.append('')
    w.append('constexpr Pair kPairs[] = {')
    for i in range(0, len(pairs), 4):
        w.append('  ' + ' '.join('{0x%08X, 0x%04X},' % x for x in pairs[i:i + 4]))
    w.append('};')
    w.append('')
    w.append('constexpr Lower kLower[] = {')
    for cp, to in lowers:
        tt = to + [0] * (3 - len(to))
        w.append('  {0x%04X, {%s}, %d},' % (cp, ', '.join('0x%04X' % x for x in tt), len(to)))
    w.append('};')
    for name, rr in (('kSigmaCased', cased_r), ('kSigmaIgnorable', ign_r), ('kAlpha', alpha_r)):
        w.append('')
        w.append('constexpr Range %s[] = {' % name)
        for i in range(0, len(rr), 5):
            w.append('  ' + ' '.join('{0x%04X, 0x%04X},' % x for x in rr[i:i + 5]))
        w.append('};')
    w.append('')
    w.append('}  // namespace text_tables')
    w.append('}  // namespace vp')
    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(w) + '\n')
    print('wrote %s: %d decompositions, %d ccc, %d pairs, %d lower, %d/%d/%d ranges' % (
        os.path.normpath(out_path), len(decomps), len(cccs), len(pairs), len(lowers), len(cased_r), len(ign_r),
        len(alpha_r)))


if __name__ == '__main__':
    main()
