// engine/lex tests: .vpl reader (DESIGN.md §5, §5.1) against fixtures made by the reference encoder
// (lex_fixture_writer.*). Regenerate the committed fixtures and SPEC_CHECK.md with
//   VP_REGEN_LEX_FIXTURES=1 ./vp_tests -tc='lex: committed fixtures*'
#include <doctest.h>

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <random>
#include <sstream>
#include <string>
#include <vector>

#include "lex_fixture_writer.h"
#include "vp/features.h"
#include "vp/lex.h"
#include "vp/sha256.h"
#include "vp/text.h"

namespace stdfs = std::filesystem;
using vp::ErrorCode;
using vp::lex::Analysis;
using vp::lex::Candidate;
using vp::lex::Lexicon;
using namespace vp::feat;

namespace {

using Bytes = std::vector<uint8_t>;

std::string fixturePath(const std::string& name) { return std::string(VP_FIXTURES_DIR) + "/lex/" + name; }

std::string tmpPath(const std::string& name) {
  stdfs::path d = stdfs::path(VP_TEST_TMP) / "lex";
  std::error_code ec;
  stdfs::create_directories(d, ec);
  return (d / name).string();
}

void writeBytes(const std::string& path, const Bytes& b) {
  std::ofstream f(path, std::ios::binary | std::ios::trunc);
  f.write(reinterpret_cast<const char*>(b.data()), static_cast<std::streamsize>(b.size()));
}

Bytes readBytes(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  return Bytes((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}

uint32_t PK(uint8_t pos, uint8_t cs = 0, uint8_t num = 0, uint8_t gen = 0, uint8_t pers = 0, uint8_t tense = 0,
           uint8_t mood = 0, uint8_t voice = 0, uint8_t deg = 0, uint8_t extra = 0) {
  Features f;
  f.pos = pos; f.case_ = cs; f.number = num; f.gender = gen; f.person = pers; f.tense = tense; f.mood = mood;
  f.voice = voice; f.degree = deg; f.extra = extra;
  return pack(f);
}

Lexicon openOk(const std::string& path) {
  auto r = Lexicon::open(path);
  REQUIRE_MESSAGE(r.ok(), r.error().message);
  return std::move(r.value());
}

std::string la(std::string_view s) { return vp::text::latin_key(s); }
std::string grc(std::string_view s) { return vp::text::greek_key(s); }

struct Named { const char* file; vp::lexfix::LexiconIn (*make)(); };
const Named kFixtures[] = {{"latin.vpl", vp::lexfix::latinFixture},
                           {"greek.vpl", vp::lexfix::greekFixture},
                           {"english.vpl", vp::lexfix::englishFixture}};

std::string hex(const uint8_t* p, size_t n) {
  std::ostringstream o;
  for (size_t i = 0; i < n; ++i) o << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(p[i]) << (i + 1 < n ? " " : "");
  return o.str();
}

uint32_t rd32(const Bytes& b, size_t at) {
  return static_cast<uint32_t>(b[at]) | (static_cast<uint32_t>(b[at + 1]) << 8) | (static_cast<uint32_t>(b[at + 2]) << 16) |
         (static_cast<uint32_t>(b[at + 3]) << 24);
}

void writeSpecCheck() {
  std::ostringstream md;
  md << "# `.vpl` spec check (generated)\n\n"
     << "Generated by `VP_REGEN_LEX_FIXTURES=1 vp_tests -tc='lex: committed fixtures*'` from the reference encoder\n"
     << "`engine/tests/lex_fixture_writer.cpp` (DESIGN.md §5). The Python packer (`tools/build_library/pack.py`) should\n"
     << "reproduce these offsets for the same input; with the STRS convention below it can reproduce the bytes.\n\n"
     << "Header fields are packed in the order of §5: magic @0, major u16 @4, minor u16 @6, lang char[8] @8,\n"
     << "section_count u32 @16, file_size u64 @20 (unaligned), sha256 u8[32] @28 (of bytes [256, file_size)), zeros\n"
     << "to 256. Section table @256: 24-byte entries {char[4] tag, u32 reserved=0, u64 offset, u64 length}, in file\n"
     << "order. Each section starts 8-byte aligned (zero gap before it); `length` is unpadded; the file ends at the end\n"
     << "of the last section. STRS: a NUL at offset 0 (empty string; \"none\" fields such as emoji_off are 0), then\n"
     << "every distinct non-empty string sorted bytewise, each NUL-terminated. FEAT: every packed word used by ANAL or\n"
     << "GENX, ascending (feat_id = index). KEYS keys and REVX keywords sorted bytewise; ANAL grouped by key; GENX\n"
     << "sorted by feat_id inside each lemma; CAND sorted by score desc, lemma id asc, sense asc.\n";
  for (const Named& n : kFixtures) {
    std::vector<vp::lexfix::SectionInfo> layout;
    const Bytes b = vp::lexfix::build(n.make(), &layout);
    md << "\n## " << n.file << "\n\n"
       << "- file size: " << b.size() << " bytes\n"
       << "- SHA-256 of the whole file: `" << vp::sha256Hex(std::string_view(reinterpret_cast<const char*>(b.data()), b.size())) << "`\n"
       << "- header bytes 0..63: `" << hex(b.data(), 64) << "`\n\n"
       << "| tag | offset | length | first u32 (count) |\n|---|---|---|---|\n";
    for (const auto& s : layout)
      md << "| " << s.tag << " | " << s.offset << " | " << s.length << " | "
         << (s.tag == "NOTE" || s.tag == "STRS" ? std::string("-") : std::to_string(rd32(b, s.offset))) << " |\n";
  }
  std::ofstream(fixturePath("SPEC_CHECK.md"), std::ios::binary | std::ios::trunc) << md.str();
}

// Calls every query on a (possibly damaged) lexicon and reads every byte of every view it returns.
size_t exercise(const Lexicon& lx, const std::vector<std::string>& keys, const std::vector<std::string>& kws) {
  size_t sum = 0;
  auto touch = [&](std::string_view s) { for (char c : s) sum += static_cast<unsigned char>(c); };
  std::vector<Analysis> an;
  std::vector<std::string_view> pv;
  std::vector<vp::lex::Sense> ss;
  std::vector<std::pair<uint32_t, std::string_view>> cs;
  std::vector<Candidate> cd;
  touch(lx.lang()); touch(lx.notice());
  (void)lx.stats();
  for (const std::string& k : keys) lx.lookup(k, an);
  for (const Analysis& a : an) { touch(a.display); touch(lx.lemma(a.lemma).head); sum += lx.feature(a.feat); }
  lx.prefix("", 100000, pv);
  lx.prefix("am", 50, pv);
  for (std::string_view s : pv) touch(s);
  const uint32_t n = std::min<uint32_t>(lx.lemmaCount(), 4096) + 3;
  for (uint32_t id = 0; id < n; ++id) {
    const vp::lex::Lemma l = lx.lemma(id);
    touch(l.head); touch(l.key); touch(l.glossEn); touch(l.glossEs); touch(l.emoji); touch(l.principal);
    ss.clear(); lx.senses(id, ss);
    for (const auto& s : ss) { touch(s.glossEn); touch(s.glossEs); touch(s.keywords); }
    cs.clear(); lx.cells(id, cs);
    for (const auto& c : cs) {
      touch(c.second);
      std::string_view f;
      if (lx.generate(id, c.first, f)) touch(f);
    }
    std::string_view f;
    if (lx.generate(id, PK(Noun, Gen, Pl), f)) touch(f);
  }
  for (const std::string& k : kws) { cd.clear(); lx.reverse(k, cd); for (const auto& c : cd) sum += c.lemma + c.score; }
  for (uint32_t i = 0; i < 300; ++i) {
    bool found = false;
    sum += lx.featId(lx.feature(static_cast<uint16_t>(i)), found);
  }
  return sum;
}

std::vector<std::string> fixtureKeys(const vp::lexfix::LexiconIn& in) {
  std::vector<std::string> keys{"", "a", "zzzz", "puell", "\xff\xff"};
  for (const auto& a : in.analyses) keys.push_back(a.key);
  return keys;
}
std::vector<std::string> fixtureKws(const vp::lexfix::LexiconIn& in) {
  std::vector<std::string> kws{"", "boy", "zzz"};
  for (const auto& c : in.candidates) kws.push_back(c.keyword);
  return kws;
}

#if defined(__linux__)
long rssKb(const char* field = "VmRSS:") {
  std::ifstream f("/proc/self/status");
  std::string line;
  const size_t n = std::char_traits<char>::length(field);
  while (std::getline(f, line))
    if (line.compare(0, n, field) == 0) return std::atol(line.c_str() + n);
  return -1;
}
#endif

}  // namespace

TEST_CASE("lex: committed fixtures match the reference encoder") {
  const bool regen = std::getenv("VP_REGEN_LEX_FIXTURES") != nullptr;
  for (const Named& n : kFixtures) {
    const Bytes built = vp::lexfix::build(n.make());
    CHECK(built == vp::lexfix::build(n.make()));   // deterministic
    if (regen) writeBytes(fixturePath(n.file), built);
    const Bytes committed = readBytes(fixturePath(n.file));
    CHECK_MESSAGE(committed == built, n.file << " differs from the encoder; regenerate with VP_REGEN_LEX_FIXTURES=1");
  }
  if (regen) writeSpecCheck();
}

TEST_CASE("lex: open and validate every fixture") {
  struct Expect { const char* file; const char* lang; uint32_t lemmas; bool full; };
  const Expect ex[] = {{"latin.vpl", "la", 6, true}, {"greek.vpl", "grc", 1, true}, {"english.vpl", "en", 4, false}};
  for (const Expect& e : ex) {
    CAPTURE(e.file);
    Lexicon lx = openOk(fixturePath(e.file));
    CHECK(lx.lang() == e.lang);
    CHECK(lx.lemmaCount() == e.lemmas);
    CHECK(lx.notice().find("Test fixture") == 0);
    CHECK(lx.verifySha256().ok());
    const vp::lex::Stats s = lx.stats();
    CHECK(s.major == 1);
    CHECK(s.fileSize == readBytes(fixturePath(e.file)).size());
    CHECK(s.hasSenses == e.full);
    CHECK(s.hasCells == e.full);
    CHECK(s.hasReverse == e.full);
    CHECK(s.keys > 0);
    CHECK(s.analyses >= s.keys);
  }
  const vp::lex::Stats s = openOk(fixturePath("latin.vpl")).stats();
  CHECK(s.cells == 13 + 42 + 36 + 2 + 1 + 2);
  CHECK(s.senses == 8);
  CHECK(s.keywords == 9);
  CHECK(s.candidates == 13);
}

TEST_CASE("lex: latin lookup hits, misses and analyses") {
  Lexicon lx = openOk(fixturePath("latin.vpl"));
  std::vector<Analysis> out;
  REQUIRE(lx.lookup("puellae", out));
  REQUIRE(out.size() == 4);   // gen sg, dat sg, nom pl, voc pl
  for (const Analysis& a : out) {
    CHECK(a.lemma == 0);
    CHECK(a.display == "puellae");
    CHECK(a.flags == vp::lex::FromTable);
  }
  std::vector<uint32_t> feats;
  for (const Analysis& a : out) feats.push_back(lx.feature(a.feat));
  std::sort(feats.begin(), feats.end());
  std::vector<uint32_t> want = {PK(Noun, Gen, Sg), PK(Noun, Dat, Sg), PK(Noun, Nom, Pl), PK(Noun, Voc, Pl)};
  std::sort(want.begin(), want.end());
  CHECK(feats == want);

  // appended, not replaced
  REQUIRE(lx.lookup("amor", out));
  REQUIRE(out.size() == 6);
  std::vector<std::string> heads;
  for (size_t i = 4; i < out.size(); ++i) heads.emplace_back(lx.lemma(out[i].lemma).head);
  std::sort(heads.begin(), heads.end());
  CHECK(heads == std::vector<std::string>{"amor", "amō"});

  out.clear();
  REQUIRE(lx.lookup(la("amāstī"), out));   // form-of page analysis
  REQUIRE(out.size() == 1);
  CHECK(out[0].flags == (vp::lex::FromFormOf | vp::lex::AltSpelling));
  CHECK(out[0].display == "amāstī");
  CHECK(lx.feature(out[0].feat) == PK(Verb, 0, Sg, 0, P2, Perfect, Indicative, Active));

  out.clear();
  REQUIRE(lx.lookup(la("puellāī"), out));
  REQUIRE(out.size() == 1);
  CHECK((out[0].flags & vp::lex::PoeticRare) != 0);
  CHECK(unpack(lx.feature(out[0].feat)).extra == Alternative);

  out.clear();
  CHECK(lx.lookup(la("Bonīs"), out));
  CHECK(out.size() == 6);   // dat/abl pl x 3 genders

  out.clear();
  for (const char* miss : {"puer", "", "puell", "puellaee", "zzz", "a", "\xce\xb1", "amo "}) {
    CAPTURE(miss);
    CHECK_FALSE(lx.lookup(miss, out));
  }
  CHECK(out.empty());
}

TEST_CASE("lex: lemma records and senses") {
  Lexicon lx = openOk(fixturePath("latin.vpl"));
  const vp::lex::Lemma p = lx.lemma(0);
  CHECK(p.id == 0);
  CHECK(p.head == "puella");
  CHECK(p.key == "puella");
  CHECK(p.glossEn == "girl");
  CHECK(p.glossEs == "niña");
  CHECK(p.emoji == "\xF0\x9F\x91\xA7");
  CHECK(p.principal == "puellae, f.");
  CHECK(p.pos == Noun);
  CHECK(p.cls == 1);
  CHECK(p.gender == F);
  CHECK(p.tier == 1);
  CHECK(p.tierSource == 2);
  CHECK(p.whitFreq == 'A');
  CHECK(p.freqRank == 412);
  CHECK(p.flags == vp::lex::HasTable);
  const vp::lex::Lemma a = lx.lemma(1);
  CHECK(a.head == "amō");
  CHECK(a.key == "amo");
  CHECK(a.principal == "amō, amāre, amāvī, amātum");
  CHECK(lx.lemma(2).emoji.empty());   // emoji_off 0 = none
  CHECK(lx.lemma(3).whitFreq == 'B');
  const vp::lex::Lemma bad = lx.lemma(6);
  CHECK(bad.id == vp::lex::kNoLemma);
  CHECK(bad.head.empty());
  CHECK(lx.lemma(0xFFFFFFFFu).id == vp::lex::kNoLemma);

  std::vector<vp::lex::Sense> ss;
  lx.senses(0, ss);
  REQUIRE(ss.size() == 2);
  CHECK(ss[0].glossEn == "girl");
  CHECK(ss[0].keywords == "girl");
  CHECK(ss[0].rank == 1);
  CHECK(ss[1].glossEn == "sweetheart, beloved");
  CHECK(ss[1].glossEs == "amada, novia");
  CHECK(ss[1].keywords == "sweetheart beloved girl");
  CHECK(ss[1].tags == (1u << 5));
  CHECK(ss[1].rank == 2);
  lx.senses(1, ss);
  CHECK(ss.size() == 4);
  CHECK(ss[2].glossEn == "to love");
  ss.clear();
  lx.senses(99, ss);
  CHECK(ss.empty());
}

TEST_CASE("lex: prefix") {
  Lexicon lx = openOk(fixturePath("latin.vpl"));
  std::vector<std::string_view> out;
  lx.prefix("puell", 100, out);
  CHECK(out == std::vector<std::string_view>{"puella", "puellae", "puellai", "puellam", "puellarum", "puellas", "puellis"});
  out.clear();
  lx.prefix("puell", 3, out);
  CHECK(out == std::vector<std::string_view>{"puella", "puellae", "puellai"});
  out.clear();
  lx.prefix("puella", 0, out);
  CHECK(out.empty());
  lx.prefix("zz", 10, out);
  CHECK(out.empty());
  lx.prefix("", 5, out);
  REQUIRE(out.size() == 5);
  CHECK(std::is_sorted(out.begin(), out.end()));
  CHECK(out[0] == "ama");
  out.clear();
  lx.prefix("", 100000, out);
  CHECK(out.size() == lx.stats().keys);
  CHECK(std::adjacent_find(out.begin(), out.end(), [](std::string_view x, std::string_view y) { return !(x < y); }) == out.end());
}

TEST_CASE("lex: generate exact cells, missing cells and cells()") {
  Lexicon lx = openOk(fixturePath("latin.vpl"));
  std::string_view f;
  REQUIRE(lx.generate(0, PK(Noun, Gen, Pl), f));
  CHECK(f == "puellārum");
  REQUIRE(lx.generate(0, PK(Noun, Gen, Sg, 0, 0, 0, 0, 0, 0, Alternative), f));
  CHECK(f == "puellāī");
  REQUIRE(lx.generate(0, PK(Noun, Gen, Sg), f));
  CHECK(f == "puellae");
  REQUIRE(lx.generate(1, PK(Verb, 0, Sg, 0, P2, Perfect, Indicative, Active), f));
  CHECK(f == "amāvistī");
  REQUIRE(lx.generate(1, PK(Verb, 0, Pl, 0, P3, Present, Indicative, Passive), f));
  CHECK(f == "amantur");
  REQUIRE(lx.generate(1, PK(Verb, Nom, Sg, MFN, 0, Present, ParticipleMood, Active), f));
  CHECK(f == "amāns");
  REQUIRE(lx.generate(2, PK(Adj, Abl, Sg, F), f));
  CHECK(f == "bonā");
  REQUIRE(lx.generate(5, PK(Noun, Gen, Sg), f));
  CHECK(f == "amōris");

  f = "unchanged";
  CHECK_FALSE(lx.generate(1, PK(Verb, 0, Sg, 0, P1, FuturePerfect, Indicative, Active), f));   // not in FEAT
  CHECK_FALSE(lx.generate(3, PK(Noun, Dat, Sg), f));        // feature exists (puella), cell missing for virgo
  CHECK_FALSE(lx.generate(0, PK(Adj, Abl, Sg, F), f));      // adjective cell asked of a noun
  CHECK_FALSE(lx.generate(6, PK(Noun, Gen, Pl), f));        // no such lemma
  CHECK_FALSE(lx.generate(0xFFFFFFFFu, PK(Noun, Gen, Pl), f));
  CHECK(f == "unchanged");

  std::vector<std::pair<uint32_t, std::string_view>> cs;
  lx.cells(1, cs);
  REQUIRE(cs.size() == 42);
  for (size_t i = 1; i < cs.size(); ++i) {
    bool a = false, b = false;
    CHECK(lx.featId(cs[i - 1].first, a) < lx.featId(cs[i].first, b));
  }
  CHECK(std::find(cs.begin(), cs.end(), std::make_pair(PK(Verb, 0, Sg, 0, P1, Present, Indicative, Active), std::string_view("amō"))) != cs.end());
  for (const auto& c : cs) {
    CHECK(unpack(c.first).pos == Verb);
    std::string_view g;
    CHECK(lx.generate(1, c.first, g));
    CHECK(g == c.second);
  }
  lx.cells(0, cs);
  CHECK(cs.size() == 42 + 13);
  cs.clear();
  lx.cells(2, cs);
  CHECK(cs.size() == 36);
  cs.clear();
  lx.cells(99, cs);
  CHECK(cs.empty());
}

TEST_CASE("lex: reverse ordering is score desc, lemma id asc") {
  Lexicon lx = openOk(fixturePath("latin.vpl"));
  std::vector<Candidate> c;
  lx.reverse("girl", c);
  REQUIRE(c.size() == 3);
  CHECK((c[0].lemma == 0 && c[0].sense == 0 && c[0].score == 160 && c[0].pos == Noun));
  CHECK((c[1].lemma == 0 && c[1].sense == 1 && c[1].score == 60));
  CHECK((c[2].lemma == 3 && c[2].sense == 0 && c[2].score == 60));
  c.clear();
  lx.reverse("love", c);
  REQUIRE(c.size() == 3);
  CHECK((c[0].lemma == 1 && c[0].score == 175 && c[0].pos == Verb));
  CHECK((c[1].lemma == 4 && c[1].score == 95));   // tie at 95: lemma 4 before lemma 5
  CHECK((c[2].lemma == 5 && c[2].score == 95));
  // appended after existing entries, which stay where they are
  std::vector<Candidate> d{{99, 0, 255, 0}};
  lx.reverse("girl", d);
  REQUIRE(d.size() == 4);
  CHECK(d[0].lemma == 99);
  CHECK(d[1].score == 160);
  c.clear();
  for (const char* miss : {"boy", "", "gir", "girls", "zzz"}) lx.reverse(miss, c);
  CHECK(c.empty());
  for (const char* kw : {"beloved", "esteem", "fond", "good", "like", "maiden", "sweetheart"}) {
    CAPTURE(kw);
    c.clear();
    lx.reverse(kw, c);
    CHECK(c.size() == 1);
  }
}

TEST_CASE("lex: feature and featId round trip") {
  Lexicon lx = openOk(fixturePath("latin.vpl"));
  const uint32_t n = lx.stats().features;
  REQUIRE(n > 0);
  for (uint32_t i = 0; i < n; ++i) {
    bool found = false;
    CHECK(lx.featId(lx.feature(static_cast<uint16_t>(i)), found) == i);
    CHECK(found);
  }
  bool found = true;
  lx.featId(0xFFFFFFFFu, found);
  CHECK_FALSE(found);
  CHECK(lx.feature(static_cast<uint16_t>(n)) == 0);
  CHECK(lx.feature(65535) == 0);
}

TEST_CASE("lex: greek Attic and non-Attic forms") {
  Lexicon lx = openOk(fixturePath("greek.vpl"));
  CHECK(lx.lemma(0).key == "ἄνθρωποσ");   // greek_key folds final sigma
  std::vector<Analysis> out;
  REQUIRE(lx.lookup(grc("ἀνθρώπου"), out));
  REQUIRE(out.size() == 1);
  CHECK(out[0].flags == vp::lex::FromTable);
  CHECK(unpack(lx.feature(out[0].feat)).extra == Attic);
  out.clear();
  REQUIRE(lx.lookup(grc("ἀνθρώποιο"), out));
  REQUIRE(out.size() == 1);
  CHECK(out[0].flags == (vp::lex::FromTable | vp::lex::NonAttic));
  CHECK(lx.feature(out[0].feat) == PK(Noun, Gen, Sg));
  out.clear();
  REQUIRE(lx.lookup(grc("ἀνθρώποιν"), out));
  CHECK(out.size() == 2);   // gen + dat dual
  out.clear();
  REQUIRE(lx.lookup(grc("ἄνθρωπος"), out));
  CHECK(out[0].display == "ἄνθρωπος");
  out.clear();
  CHECK_FALSE(lx.lookup("ἄνθρωπος", out));   // final sigma not folded: not a key
  CHECK_FALSE(lx.lookup(vp::text::greek_bare("ἄνθρωπος"), out));

  std::string_view f;
  REQUIRE(lx.generate(0, PK(Noun, Gen, Sg, 0, 0, 0, 0, 0, 0, Attic), f));
  CHECK(f == "ἀνθρώπου");
  REQUIRE(lx.generate(0, PK(Noun, Gen, Sg), f));
  CHECK(f == "ἀνθρώποιο");
  REQUIRE(lx.generate(0, PK(Noun, Dat, Dual, 0, 0, 0, 0, 0, 0, Attic), f));
  CHECK(f == "ἀνθρώποιν");
  CHECK_FALSE(lx.generate(0, PK(Noun, Acc, Sg), f));   // only the Attic accusative exists
  std::vector<Candidate> c;
  lx.reverse("man", c);
  REQUIRE(c.size() == 1);
  CHECK(c[0].score == 95);
}

TEST_CASE("lex: english morphology-only file") {
  Lexicon lx = openOk(fixturePath("english.vpl"));
  std::vector<Analysis> out;
  REQUIRE(lx.lookup("saw", out));
  REQUIRE(out.size() == 2);
  std::vector<std::string_view> heads{lx.lemma(out[0].lemma).head, lx.lemma(out[1].lemma).head};
  std::sort(heads.begin(), heads.end());
  CHECK(heads == std::vector<std::string_view>{"saw", "see"});
  out.clear();
  REQUIRE(lx.lookup("children", out));
  REQUIRE(out.size() == 1);
  CHECK(lx.lemma(out[0].lemma).head == "child");
  CHECK(lx.feature(out[0].feat) == PK(Noun, 0, Pl));
  CHECK_FALSE(lx.lookup("goed", out));
  std::string_view f;
  CHECK_FALSE(lx.generate(0, PK(Verb, 0, 0, 0, 0, Perfect), f));
  std::vector<std::pair<uint32_t, std::string_view>> cs;
  lx.cells(0, cs);
  CHECK(cs.empty());
  std::vector<Candidate> c;
  lx.reverse("go", c);
  CHECK(c.empty());
  std::vector<vp::lex::Sense> ss;
  lx.senses(0, ss);
  CHECK(ss.empty());
}

TEST_CASE("lex: features pack/unpack against features_golden.tsv") {
  std::ifstream in(std::string(VP_FIXTURES_DIR) + "/features_golden.tsv");
  if (!in) {
    MESSAGE("tests/fixtures/features_golden.tsv absent (written by LIB); skipped");
    return;
  }
  // Tag words whose meaning is one field value; other words (past, noun-from-verb, ...) are LIB's tag mapping.
  struct W { const char* w; int field; uint8_t v; };
  const W words[] = {{"nominative", 1, Nom}, {"genitive", 1, Gen}, {"dative", 1, Dat}, {"accusative", 1, Acc},
                     {"ablative", 1, Abl}, {"vocative", 1, Voc}, {"locative", 1, Loc}, {"singular", 2, Sg},
                     {"plural", 2, Pl}, {"dual", 2, Dual}, {"first-person", 4, P1}, {"second-person", 4, P2},
                     {"third-person", 4, P3}, {"indicative", 6, Indicative}, {"subjunctive", 6, Subjunctive},
                     {"imperative", 6, Imperative}, {"infinitive", 6, Infinitive}, {"optative", 6, Optative},
                     {"gerund", 6, Gerund}, {"active", 7, Active}, {"passive", 7, Passive}, {"middle", 7, Middle},
                     {"positive", 8, Positive}, {"comparative", 8, Comparative}, {"superlative", 8, Superlative}};
  const W tenses[] = {{"present", 5, Present}, {"imperfect", 5, Imperfect}, {"future", 5, Future},
                      {"perfect", 5, Perfect}, {"pluperfect", 5, Pluperfect}, {"future-perfect", 5, FuturePerfect},
                      {"aorist", 5, Aorist}};
  std::string line;
  int rows = 0;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#') continue;
    const size_t tab = line.find('\t');
    REQUIRE(tab != std::string::npos);
    const uint32_t packed = static_cast<uint32_t>(std::stoul(line.substr(tab + 1)));
    CAPTURE(line);
    CHECK(pack(unpack(packed)) == packed);
    const Features f = unpack(packed);
    const uint8_t fields[11] = {f.pos, f.case_, f.number, f.gender, f.person, f.tense, f.mood, f.voice, f.degree, f.extra, 0};
    std::istringstream ws(line.substr(0, tab));
    std::string w;
    int nTense = 0;
    uint8_t tenseV = 0;
    bool m = false, fe = false, n = false;
    while (ws >> w) {
      if (w.rfind("pos=", 0) == 0) {
        const std::string p = w.substr(4);
        if (p == "noun") CHECK(f.pos == Noun);
        if (p == "verb") CHECK(f.pos == Verb);
        if (p == "adj") CHECK(f.pos == Adj);
        if (p == "adv") CHECK(f.pos == Adv);
        if (p == "participle") CHECK(f.pos == Participle);
        continue;
      }
      m |= w == "masculine"; fe |= w == "feminine"; n |= w == "neuter";
      if (w == "supine") CHECK((f.extra & Supine) != 0);
      for (const W& x : words) if (w == x.w) CHECK(fields[x.field] == x.v);
      for (const W& x : tenses) if (w == x.w) { ++nTense; tenseV = x.v; }
    }
    if (nTense == 1) CHECK(f.tense == tenseV);
    if (m || fe || n) {
      const uint8_t g = m && fe && n ? MFN : m && fe ? MF : m && n ? MN : fe && n ? FN : m ? M : fe ? F : N;
      CHECK(f.gender == g);
    }
    ++rows;
  }
  CHECK(rows > 0);
  MESSAGE("features_golden.tsv rows checked: " << rows);
}

TEST_CASE("lex: open errors (missing, version, damaged structure)") {
  const Bytes good = readBytes(fixturePath("latin.vpl"));
  REQUIRE(good.size() > 512);
  const std::string p = tmpPath("damaged.vpl");
  auto openCode = [&](const Bytes& b) {
    writeBytes(p, b);
    auto r = Lexicon::open(p);
    return r.ok() ? ErrorCode::Ok : r.error().code;
  };
  {
    auto r = Lexicon::open(tmpPath("does-not-exist.vpl"));
    REQUIRE_FALSE(r.ok());
    CHECK(r.error().code == ErrorCode::LexiconMissing);
    CHECK_FALSE(r.error().hint.empty());
  }
  CHECK(openCode(good) == ErrorCode::Ok);
  for (uint16_t major : {0, 2, 0xFFFF}) {
    Bytes b = good;
    b[4] = static_cast<uint8_t>(major); b[5] = static_cast<uint8_t>(major >> 8);
    auto code = openCode(b);
    CHECK(code == ErrorCode::LexiconVersion);
    auto r = Lexicon::open(p);
    CHECK(r.error().message.find("version") != std::string::npos);
    CHECK_FALSE(r.error().hint.empty());
  }
  {  // minor versions are accepted
    Bytes b = good;
    b[6] = 7;
    CHECK(openCode(b) == ErrorCode::Ok);
  }
  auto corrupt = [&](Bytes b, const char* what) {
    CAPTURE(what);
    CHECK(openCode(b) == ErrorCode::LexiconCorrupt);
  };
  { Bytes b = good; b[0] = 'X'; corrupt(b, "magic"); }
  { Bytes b = good; b.push_back(0); corrupt(b, "trailing byte"); }
  { Bytes b(good.begin(), good.begin() + 255); corrupt(b, "short header"); }
  corrupt(Bytes{}, "empty file");
  corrupt(Bytes(good.size(), 0), "zero-filled");
  { Bytes b = good; b[8] = 0; corrupt(b, "empty lang"); }
  { Bytes b = good; b[16] = 0xFF; b[17] = 0xFF; corrupt(b, "section count"); }
  const uint32_t count = rd32(good, 16);
  auto entry = [&](const char* tag) {
    for (uint32_t s = 0; s < count; ++s)
      if (std::equal(tag, tag + 4, good.begin() + 256 + 24 * s)) return static_cast<size_t>(256 + 24 * s);
    FAIL("no section " << tag);
    return size_t(0);
  };
  { Bytes b = good; b[entry("KEYS") + 8] += 4; corrupt(b, "misaligned offset"); }
  { Bytes b = good; b[entry("KEYS") + 15] = 0x10; corrupt(b, "offset past end"); }
  { Bytes b = good; b[entry("REVX") + 16] += 8; corrupt(b, "length past end"); }
  { Bytes b = good; b[entry("NOTE") + 8] = 0; b[entry("NOTE") + 9] = 0; corrupt(b, "section over the header"); }
  { Bytes b = good; std::copy_n("XXXX", 4, b.begin() + static_cast<std::ptrdiff_t>(entry("KEYS"))); corrupt(b, "missing KEYS"); }
  { Bytes b = good; std::copy_n("ANAL", 4, b.begin() + static_cast<std::ptrdiff_t>(entry("KEYS"))); corrupt(b, "duplicate ANAL"); }
  { Bytes b = good; const size_t at = entry("KEYS"); b[rd32(good, at + 8) + 3] = 0x7F; corrupt(b, "KEYS count"); }
  { Bytes b = good; const size_t at = entry("LEMM"); b[rd32(good, at + 8) + 2] = 0x01; corrupt(b, "LEMM count"); }
  { Bytes b = good; const size_t at = entry("REVX"); b[rd32(good, at + 8) + 1] = 0x01; corrupt(b, "REVX count"); }
  {  // STRS must end with NUL
    Bytes b = good;
    const size_t at = entry("STRS");
    b[rd32(good, at + 8) + rd32(good, at + 16) - 1] = 'x';
    corrupt(b, "STRS tail");
  }
  {  // an unknown section tag is skipped (forward compatible minor versions); SENS is optional
    Bytes b = good;
    std::copy_n("ZZZZ", 4, b.begin() + static_cast<std::ptrdiff_t>(entry("SENS")));
    writeBytes(p, b);
    auto r = Lexicon::open(p);
    REQUIRE(r.ok());
    CHECK_FALSE(r->stats().hasSenses);
    std::vector<vp::lex::Sense> ss;
    r->senses(0, ss);
    CHECK(ss.empty());
    std::vector<Analysis> out;
    CHECK(r->lookup("puella", out));
  }
  { Bytes b = good; std::copy_n("XXXX", 4, b.begin() + static_cast<std::ptrdiff_t>(entry("NOTE"))); corrupt(b, "missing NOTE"); }
  {  // body damage passes open (no hashing there) but fails verifySha256
    Bytes b = good;
    b[good.size() - 3] ^= 0x20;
    writeBytes(p, b);
    auto r = Lexicon::open(p);
    REQUIRE(r.ok());
    auto v = r->verifySha256();
    CHECK(v.error().code == ErrorCode::LexiconCorrupt);
  }
  Lexicon empty;
  CHECK(empty.verifySha256().error().code == ErrorCode::LexiconMissing);
}

TEST_CASE("lex: move keeps the views valid; a moved-from or empty lexicon answers nothing") {
  auto r = Lexicon::open(fixturePath("latin.vpl"));
  REQUIRE(r.ok());
  Lexicon a = std::move(r.value());
  std::vector<Analysis> out;
  REQUIRE(a.lookup("puella", out));
  const std::string_view display = out[0].display;
  Lexicon b(std::move(a));
  CHECK(display == "puella");
  CHECK(b.lemma(0).head == "puella");
  CHECK_FALSE(a.lookup("puella", out));   // NOLINT(bugprone-use-after-move): defined empty state
  CHECK(a.lemmaCount() == 0);
  CHECK(a.lemma(0).id == vp::lex::kNoLemma);
  Lexicon c;
  c = std::move(b);
  CHECK(c.lemma(1).head == "amō");
  std::vector<std::string_view> pv;
  Lexicon e;
  e.prefix("", 10, pv);
  CHECK(pv.empty());
  std::vector<Candidate> cd;
  e.reverse("girl", cd);
  CHECK(cd.empty());
  CHECK(e.lang().empty());
  CHECK(e.notice().empty());
  exercise(e, {"a"}, {"girl"});
}

TEST_CASE("lex: corruption fuzz (200 truncations, 500 single-byte flips, multi-byte damage)") {
  const Bytes good = readBytes(fixturePath("latin.vpl"));
  REQUIRE(good.size() > 512);
  const auto in = vp::lexfix::latinFixture();
  const std::vector<std::string> keys = fixtureKeys(in), kws = fixtureKws(in);
  const std::string p = tmpPath("fuzz.vpl");
  std::mt19937 rng(20261006u);
  auto pick = [&](size_t n) { return std::uniform_int_distribution<size_t>(0, n - 1)(rng); };
  int opened = 0, rejected = 0, shaCaught = 0;
  auto trial = [&](const Bytes& b, bool bodyChanged) {
    writeBytes(p, b);
    auto r = Lexicon::open(p);
    if (!r.ok()) {
      const ErrorCode c = r.error().code;
      CHECK((c == ErrorCode::LexiconCorrupt || c == ErrorCode::LexiconVersion));
      ++rejected;
      return;
    }
    ++opened;
    exercise(r.value(), keys, kws);
    const bool shaOk = r->verifySha256().ok();
    if (bodyChanged) {
      CHECK_FALSE(shaOk);
      shaCaught += shaOk ? 0 : 1;
    }
  };
  for (int i = 0; i < 200; ++i) {
    const size_t cut = pick(good.size());
    trial(Bytes(good.begin(), good.begin() + static_cast<std::ptrdiff_t>(cut)), false);
  }
  CHECK(opened == 0);   // a truncated file never passes the file_size check
  for (int i = 0; i < 500; ++i) {
    Bytes b = good;
    const size_t at = pick(good.size());
    b[at] ^= static_cast<uint8_t>(1 + pick(255));
    // bytes [28,60) are the hash itself and [256, end) are hashed: either way verifySha256 must notice
    trial(b, at >= 256 || (at >= 28 && at < 60));
  }
  for (int i = 0; i < 100; ++i) {
    Bytes b = good;
    const size_t at = 256 + pick(good.size() - 256), len = 1 + pick(64);
    bool changed = false;
    for (size_t k = at; k < std::min(good.size(), at + len); ++k) { changed |= b[k] != 0; b[k] = 0; }
    trial(b, changed);
    Bytes c = good;
    for (int k = 0; k < 8; ++k) c[256 + pick(good.size() - 256)] ^= static_cast<uint8_t>(1 + pick(255));
    trial(c, c != good);
  }
  // Damage aimed at the offset fields: every u32 of every section set to large or boundary values.
  for (int i = 0; i < 300; ++i) {
    Bytes b = good;
    const size_t at = (256 + pick(good.size() - 260)) & ~size_t(3);
    const uint32_t vals[] = {0xFFFFFFFFu, 0x7FFFFFFFu, static_cast<uint32_t>(good.size()), 0x10000u, 65535u, 1u};
    const uint32_t v = vals[pick(6)];
    for (int k = 0; k < 4; ++k) b[at + k] = static_cast<uint8_t>(v >> (8 * k));
    trial(b, b != good);
  }
  MESSAGE("fuzz: " << opened << " damaged files opened and queried safely, " << rejected << " rejected at open, "
                   << shaCaught << " caught by verifySha256");
  CHECK(opened > 0);
}

TEST_CASE("lex: RSS stays flat over 1,000,000 lookups; lookup rate") {
  const uint32_t nLemmas = 50000;
  const std::string p = tmpPath("synthetic.vpl");
  std::vector<std::string> queries;
  {
    const auto in = vp::lexfix::syntheticFixture(nLemmas);
    writeBytes(p, vp::lexfix::build(in));
    std::mt19937 rng(7u);
    for (int i = 0; i < 4096; ++i) {
      if (i % 2 == 0) {
        queries.push_back(in.analyses[std::uniform_int_distribution<size_t>(0, in.analyses.size() - 1)(rng)].key);
      } else {
        std::string miss(6, 'a');
        for (char& ch : miss) ch = static_cast<char>('a' + rng() % 26);
        miss += 'q';
        queries.push_back(miss);
      }
    }
  }
  Lexicon lx = openOk(p);
  REQUIRE(lx.lemmaCount() == nLemmas);
  REQUIRE(lx.verifySha256().ok());   // touches every page once, so file-backed RSS is settled before measuring
  std::vector<Analysis> out;
  std::vector<std::string_view> pv;
  std::vector<Candidate> cd;
  std::mt19937 rng(11u);
  size_t hits = 0;
#if defined(__linux__)
  long rss10k = -1, anon10k = -1;
#endif
  const auto t0 = std::chrono::steady_clock::now();
  for (int i = 1; i <= 1000000; ++i) {
    out.clear();
    if (lx.lookup(queries[rng() & 4095], out)) ++hits;
    if (i % 1000 == 0) {   // the other queries share the buffers too
      pv.clear(); lx.prefix(queries[rng() & 4095].substr(0, 3), 16, pv);
      cd.clear(); lx.reverse("kwaab", cd);
    }
#if defined(__linux__)
    if (i == 10000) { rss10k = rssKb(); anon10k = rssKb("RssAnon:"); }
#endif
  }
  const double secs = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
  CHECK(hits > 400000);
  CHECK(hits < 600000);
  MESSAGE("lookups/s: " << static_cast<std::ptrdiff_t>(1000000 / secs) << " (" << lx.stats().keys << " keys, "
                        << lx.stats().fileSize / 1024 << " KiB file; includes 1,000 prefix + reverse calls)");
#if defined(__linux__)
  const long rss1m = rssKb(), anon1m = rssKb("RssAnon:");
  MESSAGE("VmRSS after 10k: " << rss10k << " kB, after 1M: " << rss1m << " kB; RssAnon " << anon10k << " -> " << anon1m);
  REQUIRE(rss10k > 0);
  CHECK(static_cast<double>(rss1m) <= static_cast<double>(rss10k) * 1.05);
  if (anon10k > 0) CHECK(static_cast<double>(anon1m) <= static_cast<double>(anon10k) * 1.05);
#else
  MESSAGE("RSS check skipped (not Linux)");
#endif
}
