// Generated by gui/shell/tools/webview2_subset.py from a genuine WebView2.h
// (../../edge_embedded_browser/client/win/current/WebView2.idl:, Microsoft.Web.WebView2 1.0.2903.40).
// Used only when the WebView2 SDK could not be downloaded; see gui/shell/CMakeLists.txt.
// Copyright (C) Microsoft Corporation. All rights reserved. Redistribution and use in
// source and binary forms, with or without modification, are permitted under the
// BSD-style license shipped with the Microsoft.Web.WebView2 package (LICENSE.txt).
#pragma once
#ifndef VP_WEBVIEW2_SUBSET_H
#define VP_WEBVIEW2_SUBSET_H
#include <windows.h>
#include <objidl.h>
#include <oaidl.h>
#include <eventtoken.h>

typedef interface ICoreWebView2 ICoreWebView2;
typedef interface ICoreWebView2AcceleratorKeyPressedEventHandler ICoreWebView2AcceleratorKeyPressedEventHandler;
typedef interface ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler;
typedef interface ICoreWebView2CallDevToolsProtocolMethodCompletedHandler ICoreWebView2CallDevToolsProtocolMethodCompletedHandler;
typedef interface ICoreWebView2CapturePreviewCompletedHandler ICoreWebView2CapturePreviewCompletedHandler;
typedef interface ICoreWebView2ContainsFullScreenElementChangedEventHandler ICoreWebView2ContainsFullScreenElementChangedEventHandler;
typedef interface ICoreWebView2ContentLoadingEventHandler ICoreWebView2ContentLoadingEventHandler;
typedef interface ICoreWebView2Controller ICoreWebView2Controller;
typedef interface ICoreWebView2Controller2 ICoreWebView2Controller2;
typedef interface ICoreWebView2CookieManager ICoreWebView2CookieManager;
typedef interface ICoreWebView2CreateCoreWebView2ControllerCompletedHandler ICoreWebView2CreateCoreWebView2ControllerCompletedHandler;
typedef interface ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler;
typedef interface ICoreWebView2DOMContentLoadedEventHandler ICoreWebView2DOMContentLoadedEventHandler;
typedef interface ICoreWebView2Deferral ICoreWebView2Deferral;
typedef interface ICoreWebView2DevToolsProtocolEventReceiver ICoreWebView2DevToolsProtocolEventReceiver;
typedef interface ICoreWebView2DocumentTitleChangedEventHandler ICoreWebView2DocumentTitleChangedEventHandler;
typedef interface ICoreWebView2Environment ICoreWebView2Environment;
typedef interface ICoreWebView2EnvironmentOptions ICoreWebView2EnvironmentOptions;
typedef interface ICoreWebView2ExecuteScriptCompletedHandler ICoreWebView2ExecuteScriptCompletedHandler;
typedef interface ICoreWebView2File ICoreWebView2File;
typedef interface ICoreWebView2FocusChangedEventHandler ICoreWebView2FocusChangedEventHandler;
typedef interface ICoreWebView2HistoryChangedEventHandler ICoreWebView2HistoryChangedEventHandler;
typedef interface ICoreWebView2HttpRequestHeaders ICoreWebView2HttpRequestHeaders;
typedef interface ICoreWebView2MoveFocusRequestedEventHandler ICoreWebView2MoveFocusRequestedEventHandler;
typedef interface ICoreWebView2NavigationCompletedEventHandler ICoreWebView2NavigationCompletedEventHandler;
typedef interface ICoreWebView2NavigationStartingEventArgs ICoreWebView2NavigationStartingEventArgs;
typedef interface ICoreWebView2NavigationStartingEventHandler ICoreWebView2NavigationStartingEventHandler;
typedef interface ICoreWebView2NewBrowserVersionAvailableEventHandler ICoreWebView2NewBrowserVersionAvailableEventHandler;
typedef interface ICoreWebView2NewWindowRequestedEventArgs ICoreWebView2NewWindowRequestedEventArgs;
typedef interface ICoreWebView2NewWindowRequestedEventHandler ICoreWebView2NewWindowRequestedEventHandler;
typedef interface ICoreWebView2ObjectCollectionView ICoreWebView2ObjectCollectionView;
typedef interface ICoreWebView2PermissionRequestedEventHandler ICoreWebView2PermissionRequestedEventHandler;
typedef interface ICoreWebView2ProcessFailedEventArgs ICoreWebView2ProcessFailedEventArgs;
typedef interface ICoreWebView2ProcessFailedEventHandler ICoreWebView2ProcessFailedEventHandler;
typedef interface ICoreWebView2ScriptDialogOpeningEventHandler ICoreWebView2ScriptDialogOpeningEventHandler;
typedef interface ICoreWebView2Settings ICoreWebView2Settings;
typedef interface ICoreWebView2Settings2 ICoreWebView2Settings2;
typedef interface ICoreWebView2Settings3 ICoreWebView2Settings3;
typedef interface ICoreWebView2Settings4 ICoreWebView2Settings4;
typedef interface ICoreWebView2Settings5 ICoreWebView2Settings5;
typedef interface ICoreWebView2Settings6 ICoreWebView2Settings6;
typedef interface ICoreWebView2Settings7 ICoreWebView2Settings7;
typedef interface ICoreWebView2Settings8 ICoreWebView2Settings8;
typedef interface ICoreWebView2SourceChangedEventHandler ICoreWebView2SourceChangedEventHandler;
typedef interface ICoreWebView2TrySuspendCompletedHandler ICoreWebView2TrySuspendCompletedHandler;
typedef interface ICoreWebView2WebMessageReceivedEventArgs ICoreWebView2WebMessageReceivedEventArgs;
typedef interface ICoreWebView2WebMessageReceivedEventArgs2 ICoreWebView2WebMessageReceivedEventArgs2;
typedef interface ICoreWebView2WebMessageReceivedEventHandler ICoreWebView2WebMessageReceivedEventHandler;
typedef interface ICoreWebView2WebResourceRequest ICoreWebView2WebResourceRequest;
typedef interface ICoreWebView2WebResourceRequestedEventHandler ICoreWebView2WebResourceRequestedEventHandler;
typedef interface ICoreWebView2WebResourceResponse ICoreWebView2WebResourceResponse;
typedef interface ICoreWebView2WebResourceResponseReceivedEventHandler ICoreWebView2WebResourceResponseReceivedEventHandler;
typedef interface ICoreWebView2WindowCloseRequestedEventHandler ICoreWebView2WindowCloseRequestedEventHandler;
typedef interface ICoreWebView2WindowFeatures ICoreWebView2WindowFeatures;
typedef interface ICoreWebView2ZoomFactorChangedEventHandler ICoreWebView2ZoomFactorChangedEventHandler;
typedef interface ICoreWebView2_2 ICoreWebView2_2;
typedef interface ICoreWebView2_3 ICoreWebView2_3;

typedef  
enum COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT
    {
        COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG	= 0,
        COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG	= ( COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG + 1 ) 
    } 	COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT;

typedef struct COREWEBVIEW2_COLOR
    {
    BYTE A;
    BYTE R;
    BYTE G;
    BYTE B;
    } 	COREWEBVIEW2_COLOR;

typedef  
enum COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND
    {
        COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY	= 0,
        COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW	= ( COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY + 1 ) ,
        COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS	= ( COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW + 1 ) 
    } 	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND;

typedef  
enum COREWEBVIEW2_MOVE_FOCUS_REASON
    {
        COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC	= 0,
        COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT	= ( COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC + 1 ) ,
        COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS	= ( COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT + 1 ) 
    } 	COREWEBVIEW2_MOVE_FOCUS_REASON;

typedef  
enum COREWEBVIEW2_PDF_TOOLBAR_ITEMS
    {
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE	= 0,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE	= 0x1,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT	= 0x2,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS	= 0x4,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN	= 0x8,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT	= 0x10,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE	= 0x20,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE	= 0x40,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT	= 0x80,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS	= 0x100,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR	= 0x200,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH	= 0x400,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN	= 0x800,
        COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS	= 0x1000
    } 	COREWEBVIEW2_PDF_TOOLBAR_ITEMS;

typedef  
enum COREWEBVIEW2_PROCESS_FAILED_KIND
    {
        COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED	= 0,
        COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_GPU_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_GPU_PROCESS_EXITED + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED + 1 ) ,
        COREWEBVIEW2_PROCESS_FAILED_KIND_UNKNOWN_PROCESS_EXITED	= ( COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED + 1 ) 
    } 	COREWEBVIEW2_PROCESS_FAILED_KIND;

typedef  
enum COREWEBVIEW2_WEB_RESOURCE_CONTEXT
    {
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL	= 0,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING + 1 ) ,
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER	= ( COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT + 1 ) 
    } 	COREWEBVIEW2_WEB_RESOURCE_CONTEXT;

// ICoreWebView2Environment (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Environment = {0xb96d755e,0x0319,0x4e92,{0xa2,0x96,0x23,0x43,0x6f,0x46,0xa1,0xfc}};
MIDL_INTERFACE("b96d755e-0319-4e92-a296-23436f46a1fc")
ICoreWebView2Environment : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE CreateCoreWebView2Controller( HWND parentWindow, ICoreWebView2CreateCoreWebView2ControllerCompletedHandler *handler) = 0;
    virtual HRESULT STDMETHODCALLTYPE CreateWebResourceResponse( IStream *content, int statusCode, LPCWSTR reasonPhrase, LPCWSTR headers, ICoreWebView2WebResourceResponse **response) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_BrowserVersionString( LPWSTR *versionInfo) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_NewBrowserVersionAvailable( ICoreWebView2NewBrowserVersionAvailableEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_NewBrowserVersionAvailable( EventRegistrationToken token) = 0;
};

// ICoreWebView2Controller (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Controller = {0x4d00c0d1,0x9434,0x4eb6,{0x80,0x78,0x86,0x97,0xa5,0x60,0x33,0x4f}};
MIDL_INTERFACE("4d00c0d1-9434-4eb6-8078-8697a560334f")
ICoreWebView2Controller : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_IsVisible( BOOL *isVisible) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsVisible( BOOL isVisible) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_Bounds( RECT *bounds) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_Bounds( RECT bounds) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_ZoomFactor( double *zoomFactor) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_ZoomFactor( double zoomFactor) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_ZoomFactorChanged( ICoreWebView2ZoomFactorChangedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_ZoomFactorChanged( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE SetBoundsAndZoomFactor( RECT bounds, double zoomFactor) = 0;
    virtual HRESULT STDMETHODCALLTYPE MoveFocus( COREWEBVIEW2_MOVE_FOCUS_REASON reason) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_MoveFocusRequested( ICoreWebView2MoveFocusRequestedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_MoveFocusRequested( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_GotFocus( ICoreWebView2FocusChangedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_GotFocus( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_LostFocus( ICoreWebView2FocusChangedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_LostFocus( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_AcceleratorKeyPressed( ICoreWebView2AcceleratorKeyPressedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_AcceleratorKeyPressed( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_ParentWindow( HWND *parentWindow) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_ParentWindow( HWND parentWindow) = 0;
    virtual HRESULT STDMETHODCALLTYPE NotifyParentWindowPositionChanged( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE Close( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_CoreWebView2( ICoreWebView2 **coreWebView2) = 0;
};

// ICoreWebView2Controller2 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Controller2 = {0xc979903e,0xd4ca,0x4228,{0x92,0xeb,0x47,0xee,0x3f,0xa9,0x6e,0xab}};
MIDL_INTERFACE("c979903e-d4ca-4228-92eb-47ee3fa96eab")
ICoreWebView2Controller2 : public ICoreWebView2Controller
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_DefaultBackgroundColor( COREWEBVIEW2_COLOR *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_DefaultBackgroundColor( COREWEBVIEW2_COLOR value) = 0;
};

// ICoreWebView2 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2 = {0x76eceacb,0x0462,0x4d94,{0xac,0x83,0x42,0x3a,0x67,0x93,0x77,0x5e}};
MIDL_INTERFACE("76eceacb-0462-4d94-ac83-423a6793775e")
ICoreWebView2 : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_Settings( ICoreWebView2Settings **settings) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_Source( LPWSTR *uri) = 0;
    virtual HRESULT STDMETHODCALLTYPE Navigate( LPCWSTR uri) = 0;
    virtual HRESULT STDMETHODCALLTYPE NavigateToString( LPCWSTR htmlContent) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_NavigationStarting( ICoreWebView2NavigationStartingEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_NavigationStarting( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_ContentLoading( ICoreWebView2ContentLoadingEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_ContentLoading( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_SourceChanged( ICoreWebView2SourceChangedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_SourceChanged( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_HistoryChanged( ICoreWebView2HistoryChangedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_HistoryChanged( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_NavigationCompleted( ICoreWebView2NavigationCompletedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_NavigationCompleted( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_FrameNavigationStarting( ICoreWebView2NavigationStartingEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_FrameNavigationStarting( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_FrameNavigationCompleted( ICoreWebView2NavigationCompletedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_FrameNavigationCompleted( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_ScriptDialogOpening( ICoreWebView2ScriptDialogOpeningEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_ScriptDialogOpening( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_PermissionRequested( ICoreWebView2PermissionRequestedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_PermissionRequested( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_ProcessFailed( ICoreWebView2ProcessFailedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_ProcessFailed( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE AddScriptToExecuteOnDocumentCreated( LPCWSTR javaScript, ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler *handler) = 0;
    virtual HRESULT STDMETHODCALLTYPE RemoveScriptToExecuteOnDocumentCreated( LPCWSTR id) = 0;
    virtual HRESULT STDMETHODCALLTYPE ExecuteScript( LPCWSTR javaScript, ICoreWebView2ExecuteScriptCompletedHandler *handler) = 0;
    virtual HRESULT STDMETHODCALLTYPE CapturePreview( COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT imageFormat, IStream *imageStream, ICoreWebView2CapturePreviewCompletedHandler *handler) = 0;
    virtual HRESULT STDMETHODCALLTYPE Reload( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE PostWebMessageAsJson( LPCWSTR webMessageAsJson) = 0;
    virtual HRESULT STDMETHODCALLTYPE PostWebMessageAsString( LPCWSTR webMessageAsString) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_WebMessageReceived( ICoreWebView2WebMessageReceivedEventHandler *handler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_WebMessageReceived( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE CallDevToolsProtocolMethod( LPCWSTR methodName, LPCWSTR parametersAsJson, ICoreWebView2CallDevToolsProtocolMethodCompletedHandler *handler) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_BrowserProcessId( UINT32 *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_CanGoBack( BOOL *canGoBack) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_CanGoForward( BOOL *canGoForward) = 0;
    virtual HRESULT STDMETHODCALLTYPE GoBack( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE GoForward( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE GetDevToolsProtocolEventReceiver( LPCWSTR eventName, ICoreWebView2DevToolsProtocolEventReceiver **receiver) = 0;
    virtual HRESULT STDMETHODCALLTYPE Stop( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_NewWindowRequested( ICoreWebView2NewWindowRequestedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_NewWindowRequested( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_DocumentTitleChanged( ICoreWebView2DocumentTitleChangedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_DocumentTitleChanged( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_DocumentTitle( LPWSTR *title) = 0;
    virtual HRESULT STDMETHODCALLTYPE AddHostObjectToScript( LPCWSTR name, VARIANT *object) = 0;
    virtual HRESULT STDMETHODCALLTYPE RemoveHostObjectFromScript( LPCWSTR name) = 0;
    virtual HRESULT STDMETHODCALLTYPE OpenDevToolsWindow( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_ContainsFullScreenElementChanged( ICoreWebView2ContainsFullScreenElementChangedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_ContainsFullScreenElementChanged( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_ContainsFullScreenElement( BOOL *containsFullScreenElement) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_WebResourceRequested( ICoreWebView2WebResourceRequestedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_WebResourceRequested( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE AddWebResourceRequestedFilter( const LPCWSTR uri, const COREWEBVIEW2_WEB_RESOURCE_CONTEXT resourceContext) = 0;
    virtual HRESULT STDMETHODCALLTYPE RemoveWebResourceRequestedFilter( const LPCWSTR uri, const COREWEBVIEW2_WEB_RESOURCE_CONTEXT resourceContext) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_WindowCloseRequested( ICoreWebView2WindowCloseRequestedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_WindowCloseRequested( EventRegistrationToken token) = 0;
};

// ICoreWebView2_2 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2_2 = {0x9e8f0cf8,0xe670,0x4b5e,{0xb2,0xbc,0x73,0xe0,0x61,0xe3,0x18,0x4c}};
MIDL_INTERFACE("9e8f0cf8-e670-4b5e-b2bc-73e061e3184c")
ICoreWebView2_2 : public ICoreWebView2
{
public:
    virtual HRESULT STDMETHODCALLTYPE add_WebResourceResponseReceived( ICoreWebView2WebResourceResponseReceivedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_WebResourceResponseReceived( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE NavigateWithWebResourceRequest( ICoreWebView2WebResourceRequest *request) = 0;
    virtual HRESULT STDMETHODCALLTYPE add_DOMContentLoaded( ICoreWebView2DOMContentLoadedEventHandler *eventHandler, EventRegistrationToken *token) = 0;
    virtual HRESULT STDMETHODCALLTYPE remove_DOMContentLoaded( EventRegistrationToken token) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_CookieManager( ICoreWebView2CookieManager **cookieManager) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_Environment( ICoreWebView2Environment **environment) = 0;
};

// ICoreWebView2_3 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2_3 = {0xa0d6df20,0x3b92,0x416d,{0xaa,0x0c,0x43,0x7a,0x9c,0x72,0x78,0x57}};
MIDL_INTERFACE("a0d6df20-3b92-416d-aa0c-437a9c727857")
ICoreWebView2_3 : public ICoreWebView2_2
{
public:
    virtual HRESULT STDMETHODCALLTYPE TrySuspend( ICoreWebView2TrySuspendCompletedHandler *handler) = 0;
    virtual HRESULT STDMETHODCALLTYPE Resume( void) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsSuspended( BOOL *isSuspended) = 0;
    virtual HRESULT STDMETHODCALLTYPE SetVirtualHostNameToFolderMapping( LPCWSTR hostName, LPCWSTR folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind) = 0;
    virtual HRESULT STDMETHODCALLTYPE ClearVirtualHostNameToFolderMapping( LPCWSTR hostName) = 0;
};

// ICoreWebView2Settings (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings = {0xe562e4f0,0xd7fa,0x43ac,{0x8d,0x71,0xc0,0x51,0x50,0x49,0x9f,0x00}};
MIDL_INTERFACE("e562e4f0-d7fa-43ac-8d71-c05150499f00")
ICoreWebView2Settings : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_IsScriptEnabled( BOOL *isScriptEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsScriptEnabled( BOOL isScriptEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsWebMessageEnabled( BOOL *isWebMessageEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsWebMessageEnabled( BOOL isWebMessageEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_AreDefaultScriptDialogsEnabled( BOOL *areDefaultScriptDialogsEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_AreDefaultScriptDialogsEnabled( BOOL areDefaultScriptDialogsEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsStatusBarEnabled( BOOL *isStatusBarEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsStatusBarEnabled( BOOL isStatusBarEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_AreDevToolsEnabled( BOOL *areDevToolsEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_AreDevToolsEnabled( BOOL areDevToolsEnabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_AreDefaultContextMenusEnabled( BOOL *enabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_AreDefaultContextMenusEnabled( BOOL enabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_AreHostObjectsAllowed( BOOL *allowed) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_AreHostObjectsAllowed( BOOL allowed) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsZoomControlEnabled( BOOL *enabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsZoomControlEnabled( BOOL enabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsBuiltInErrorPageEnabled( BOOL *enabled) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsBuiltInErrorPageEnabled( BOOL enabled) = 0;
};

// ICoreWebView2Settings2 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings2 = {0xee9a0f68,0xf46c,0x4e32,{0xac,0x23,0xef,0x8c,0xac,0x22,0x4d,0x2a}};
MIDL_INTERFACE("ee9a0f68-f46c-4e32-ac23-ef8cac224d2a")
ICoreWebView2Settings2 : public ICoreWebView2Settings
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_UserAgent( LPWSTR *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_UserAgent( LPCWSTR value) = 0;
};

// ICoreWebView2Settings3 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings3 = {0xfdb5ab74,0xaf33,0x4854,{0x84,0xf0,0x0a,0x63,0x1d,0xeb,0x5e,0xba}};
MIDL_INTERFACE("fdb5ab74-af33-4854-84f0-0a631deb5eba")
ICoreWebView2Settings3 : public ICoreWebView2Settings2
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_AreBrowserAcceleratorKeysEnabled( BOOL *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_AreBrowserAcceleratorKeysEnabled( BOOL value) = 0;
};

// ICoreWebView2Settings4 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings4 = {0xcb56846c,0x4168,0x4d53,{0xb0,0x4f,0x03,0xb6,0xd6,0x79,0x6f,0xf2}};
MIDL_INTERFACE("cb56846c-4168-4d53-b04f-03b6d6796ff2")
ICoreWebView2Settings4 : public ICoreWebView2Settings3
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_IsPasswordAutosaveEnabled( BOOL *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsPasswordAutosaveEnabled( BOOL value) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsGeneralAutofillEnabled( BOOL *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsGeneralAutofillEnabled( BOOL value) = 0;
};

// ICoreWebView2Settings5 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings5 = {0x183e7052,0x1d03,0x43a0,{0xab,0x99,0x98,0xe0,0x43,0xb6,0x6b,0x39}};
MIDL_INTERFACE("183e7052-1d03-43a0-ab99-98e043b66b39")
ICoreWebView2Settings5 : public ICoreWebView2Settings4
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_IsPinchZoomEnabled( BOOL *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsPinchZoomEnabled( BOOL value) = 0;
};

// ICoreWebView2Settings6 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings6 = {0x11cb3acd,0x9bc8,0x43b8,{0x83,0xbf,0xf4,0x07,0x53,0x71,0x4f,0x87}};
MIDL_INTERFACE("11cb3acd-9bc8-43b8-83bf-f40753714f87")
ICoreWebView2Settings6 : public ICoreWebView2Settings5
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_IsSwipeNavigationEnabled( BOOL *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsSwipeNavigationEnabled( BOOL value) = 0;
};

// ICoreWebView2Settings7 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings7 = {0x488dc902,0x35ef,0x42d2,{0xbc,0x7d,0x94,0xb6,0x5c,0x4b,0xc4,0x9c}};
MIDL_INTERFACE("488dc902-35ef-42d2-bc7d-94b65c4bc49c")
ICoreWebView2Settings7 : public ICoreWebView2Settings6
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_HiddenPdfToolbarItems( COREWEBVIEW2_PDF_TOOLBAR_ITEMS *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_HiddenPdfToolbarItems( COREWEBVIEW2_PDF_TOOLBAR_ITEMS value) = 0;
};

// ICoreWebView2Settings8 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2Settings8 = {0x9e6b0e8f,0x86ad,0x4e81,{0x81,0x47,0xa9,0xb5,0xed,0xb6,0x86,0x50}};
MIDL_INTERFACE("9e6b0e8f-86ad-4e81-8147-a9b5edb68650")
ICoreWebView2Settings8 : public ICoreWebView2Settings7
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_IsReputationCheckingRequired( BOOL *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_IsReputationCheckingRequired( BOOL value) = 0;
};

// ICoreWebView2WebMessageReceivedEventArgs (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2WebMessageReceivedEventArgs = {0x0f99a40c,0xe962,0x4207,{0x9e,0x92,0xe3,0xd5,0x42,0xef,0xf8,0x49}};
MIDL_INTERFACE("0f99a40c-e962-4207-9e92-e3d542eff849")
ICoreWebView2WebMessageReceivedEventArgs : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_Source( LPWSTR *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_WebMessageAsJson( LPWSTR *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE TryGetWebMessageAsString( LPWSTR *value) = 0;
};

// ICoreWebView2WebMessageReceivedEventArgs2 (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2WebMessageReceivedEventArgs2 = {0x06fc7ab7,0xc90c,0x4297,{0x93,0x89,0x33,0xca,0x01,0xcf,0x6d,0x5e}};
MIDL_INTERFACE("06fc7ab7-c90c-4297-9389-33ca01cf6d5e")
ICoreWebView2WebMessageReceivedEventArgs2 : public ICoreWebView2WebMessageReceivedEventArgs
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_AdditionalObjects( ICoreWebView2ObjectCollectionView **value) = 0;
};

// ICoreWebView2ObjectCollectionView (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2ObjectCollectionView = {0x0f36fd87,0x4f69,0x4415,{0x98,0xda,0x88,0x8f,0x89,0xfb,0x9a,0x33}};
MIDL_INTERFACE("0f36fd87-4f69-4415-98da-888f89fb9a33")
ICoreWebView2ObjectCollectionView : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_Count( UINT32 *value) = 0;
    virtual HRESULT STDMETHODCALLTYPE GetValueAtIndex( UINT32 index, IUnknown **value) = 0;
};

// ICoreWebView2File (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2File = {0xf2c19559,0x6bc1,0x4583,{0xa7,0x57,0x90,0x02,0x1b,0xe9,0xaf,0xec}};
MIDL_INTERFACE("f2c19559-6bc1-4583-a757-90021be9afec")
ICoreWebView2File : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_Path( LPWSTR *value) = 0;
};

// ICoreWebView2NavigationStartingEventArgs (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2NavigationStartingEventArgs = {0x5b495469,0xe119,0x438a,{0x9b,0x18,0x76,0x04,0xf2,0x5f,0x2e,0x49}};
MIDL_INTERFACE("5b495469-e119-438a-9b18-7604f25f2e49")
ICoreWebView2NavigationStartingEventArgs : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_Uri( LPWSTR *uri) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsUserInitiated( BOOL *isUserInitiated) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsRedirected( BOOL *isRedirected) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_RequestHeaders( ICoreWebView2HttpRequestHeaders **requestHeaders) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_Cancel( BOOL *cancel) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_Cancel( BOOL cancel) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_NavigationId( UINT64 *navigationId) = 0;
};

// ICoreWebView2NewWindowRequestedEventArgs (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2NewWindowRequestedEventArgs = {0x34acb11c,0xfc37,0x4418,{0x91,0x32,0xf9,0xc2,0x1d,0x1e,0xaf,0xb9}};
MIDL_INTERFACE("34acb11c-fc37-4418-9132-f9c21d1eafb9")
ICoreWebView2NewWindowRequestedEventArgs : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_Uri( LPWSTR *uri) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_NewWindow( ICoreWebView2 *newWindow) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_NewWindow( ICoreWebView2 **newWindow) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_Handled( BOOL handled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_Handled( BOOL *handled) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_IsUserInitiated( BOOL *isUserInitiated) = 0;
    virtual HRESULT STDMETHODCALLTYPE GetDeferral( ICoreWebView2Deferral **deferral) = 0;
    virtual HRESULT STDMETHODCALLTYPE get_WindowFeatures( ICoreWebView2WindowFeatures **value) = 0;
};

// ICoreWebView2ProcessFailedEventArgs (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2ProcessFailedEventArgs = {0x8155a9a4,0x1474,0x4a86,{0x8c,0xae,0x15,0x1b,0x0f,0xa6,0xb8,0xca}};
MIDL_INTERFACE("8155a9a4-1474-4a86-8cae-151b0fa6b8ca")
ICoreWebView2ProcessFailedEventArgs : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_ProcessFailedKind( COREWEBVIEW2_PROCESS_FAILED_KIND *value) = 0;
};

// ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler = {0x4e8a3389,0xc9d8,0x4bd2,{0xb6,0xb5,0x12,0x4f,0xee,0x6c,0xc1,0x4d}};
MIDL_INTERFACE("4e8a3389-c9d8-4bd2-b6b5-124fee6cc14d")
ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Invoke( HRESULT errorCode, ICoreWebView2Environment *result) = 0;
};

// ICoreWebView2CreateCoreWebView2ControllerCompletedHandler (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2CreateCoreWebView2ControllerCompletedHandler = {0x6c4819f3,0xc9b7,0x4260,{0x81,0x27,0xc9,0xf5,0xbd,0xe7,0xf6,0x8c}};
MIDL_INTERFACE("6c4819f3-c9b7-4260-8127-c9f5bde7f68c")
ICoreWebView2CreateCoreWebView2ControllerCompletedHandler : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Invoke( HRESULT errorCode, ICoreWebView2Controller *result) = 0;
};

// ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler = {0xb99369f3,0x9b11,0x47b5,{0xbc,0x6f,0x8e,0x78,0x95,0xfc,0xea,0x17}};
MIDL_INTERFACE("b99369f3-9b11-47b5-bc6f-8e7895fcea17")
ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Invoke( HRESULT errorCode, LPCWSTR result) = 0;
};

// ICoreWebView2WebMessageReceivedEventHandler (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2WebMessageReceivedEventHandler = {0x57213f19,0x00e6,0x49fa,{0x8e,0x07,0x89,0x8e,0xa0,0x1e,0xcb,0xd2}};
MIDL_INTERFACE("57213f19-00e6-49fa-8e07-898ea01ecbd2")
ICoreWebView2WebMessageReceivedEventHandler : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Invoke( ICoreWebView2 *sender, ICoreWebView2WebMessageReceivedEventArgs *args) = 0;
};

// ICoreWebView2NavigationStartingEventHandler (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2NavigationStartingEventHandler = {0x9adbe429,0xf36d,0x432b,{0x9d,0xdc,0xf8,0x88,0x1f,0xbd,0x76,0xe3}};
MIDL_INTERFACE("9adbe429-f36d-432b-9ddc-f8881fbd76e3")
ICoreWebView2NavigationStartingEventHandler : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Invoke( ICoreWebView2 *sender, ICoreWebView2NavigationStartingEventArgs *args) = 0;
};

// ICoreWebView2NewWindowRequestedEventHandler (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2NewWindowRequestedEventHandler = {0xd4c185fe,0xc81c,0x4989,{0x97,0xaf,0x2d,0x3f,0xa7,0xab,0x56,0x51}};
MIDL_INTERFACE("d4c185fe-c81c-4989-97af-2d3fa7ab5651")
ICoreWebView2NewWindowRequestedEventHandler : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Invoke( ICoreWebView2 *sender, ICoreWebView2NewWindowRequestedEventArgs *args) = 0;
};

// ICoreWebView2ProcessFailedEventHandler (header)
EXTERN_C __declspec(selectany) const IID IID_ICoreWebView2ProcessFailedEventHandler = {0x79e0aea4,0x990b,0x42d9,{0xaa,0x1d,0x0f,0xcc,0x2e,0x5b,0xc7,0xf1}};
MIDL_INTERFACE("79e0aea4-990b-42d9-aa1d-0fcc2e5bc7f1")
ICoreWebView2ProcessFailedEventHandler : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Invoke( ICoreWebView2 *sender, ICoreWebView2ProcessFailedEventArgs *args) = 0;
};

#endif  // VP_WEBVIEW2_SUBSET_H
